lucide-icons/lucide

icons/network.svg

Related: https://github.com/feathericons/feather/pull/652, https://github.com/feathericons/feather/issues/94

feat: Add `network` icon

---

icons/git-commit.svg

- Added padding of 2px (same as the other git icons).
- Made the circle the same size as the other git icons.

refactor: Update `git-commit` icon

---

icons/redo.svg
icons/undo.svg

Possible response to [#60](https://github.com/feathericons/feather/issues/60) based on a suggestion to use `refresh-cw` as a starting point.

feat: Add `undo` and `redo` icons

---

icons/align-center.svg
icons/align-justify.svg
icons/align-left.svg
icons/align-right.svg

According to the thread in #102, the align icons needs an redesign.
I inspired the icons from the figma icons. 
I think these icons are more simplified and fit better with the other icons as wel.

Refactor text-align icons

---

site/package.json
site/src/components/IconDetailOverlay.tsx
site/yarn.lock

This fixes #124 .  The bug was the result of a regression in Chakra-UI. Updating to the latest release fixes it.  I also added a close button so the toast can be closed manually (note - even the close button wouldn't work on the previous version of Chakra) (see https://github.com/chakra-ui/chakra-ui/issues/2345)

Fix: Bump Chakra-UI and add close button to toast

---

icons/plane.svg
tags.json

feat: Add plane icon

---

icons/timer.svg
tags.json

feat: Add timer icon

---

package.json
scripts/helpers.js
scripts/optimizeSvgs.js
scripts/render/processSvg.js

- Switch `SVGO.optimize` function to returning a promise instead of accepting a callback - https://github.com/svg/svgo/releases/tag/v1.0.0
- Pin prettier to the last version before `1.18.0` which removed the self closing JSX brackets.  On a clean install without a `package-lock.json` a higher version would automatically be installed - https://prettier.io/blog/2019/06/06/1.18.0.html#stop-converting-empty-jsx-elements-to-self-closing-elements-6127-by-duailibe
- Add `{ parser: babel }` option to `format` to avoid warnings on each iteration
- Fix some incorrect arguments for writing the SVGs to disk

Fix optimizeSvgs script

---

package.json
scripts/optimizeStagedSvgs.js
yarn.lock

I added a pre-commit hook using husky and lint staged to run the `optimizeSvgs` script on only the staged SVGs when a contributor commits new icons.  They should probably do this before contributing anyway as it can sometimes change the way an icon looks, but this will aid in keeping the whole project consistent.
Mentioned here: https://github.com/lucide-icons/lucide/pull/160#issuecomment-753416087

Add hook to optimize staged SVGs before commit

---

icons/server-crash.svg

Add `server-crash` icon
_Yipeee! My first contribution to this repository_

Add server-crash icon

---

icons/sprout.svg

Design From: https://github.com/feathericons/feather/issues/968
Thanks to @neelchanda for providing the image, I adjusted the icon a bit to match our guidelines.
100% ![image](https://user-images.githubusercontent.com/11825403/102716601-30458480-42dd-11eb-8334-e031af902ca3.png)

Add sprout icon

---

site/src/lib/fetchAllContributors.ts

Fix duplicated contributors on site

---

icons/alarm-minus.svg
icons/alarm-plus.svg

The plus and the minus look a bit to big on 100%.
I shrink them a bit.

Refactor Alarm icons, shrink the plus and minus size

---

packages/lucide-react/build-types.js
packages/lucide-react/package.json
scripts/render/renderIconNodes.js

Solves the React.js part of issue #226 
The types in LucideProps are declared so they match the props mentioned in https://github.com/lucide-icons/lucide/blob/master/packages/lucide-react/README.md#props. They could be removed, since they're already present in SVGAttributes.

lucide-react - Generate types for all exported icons

---

icons/check-circle-2.svg

| zoom | 100% |
| --- | --- |
| <img width="460" alt="CleanShot 2021-02-25 at 16 07 32@2x" src="https://user-images.githubusercontent.com/29014463/109141562-e1f0ae00-7783-11eb-8801-b76a787e5551.png"> | <img width="43" alt="CleanShot 2021-02-25 at 16 07 40@2x" src="https://user-images.githubusercontent.com/29014463/109141589-e917bc00-7783-11eb-8544-678fe387c6e9.png"> |

add circle-check-2 icon

---

icons/campsite.svg
icons/tent.svg
tags.json

name | about | labels
-- | -- | --
New icon | Add a new icon to the library | 🎨 <icon
- **Name of the icon** : Campsite
- **Tags (alternative names for this icon)** (add them in tags.json) :  tent
- **What is the purpose of this icon?** : Depicting holidays or outdoor activities. Can be used in maps as well.
- **100% scale preview** : ![campsite](https://user-images.githubusercontent.com/13321277/118512116-d1bcef00-b732-11eb-93e8-8b5f2f4d8869.png)
- **Have you considered alternative possibilities** for its naming or design? : It's roughly based on [#61 at feather](https://github.com/feathericons/feather/issues/61), but I feel this one is slightly more recognizable as a tent.

Add tent icon

---

packages/lucide-preact/package.json
packages/lucide-react/package.json
packages/lucide-vue-next/package.json
packages/lucide-vue/package.json

Closes #332
`sideEffects` was missing in the package.jsons in the following packages:
- `lucide-react`
- `lucide-preact`
- `lucide-vue`
- `lucide-vue-next`
I added it so packages will be three shakable.

Add sideEffects false in package jsons

---

packages/lucide-react/scripts/buildTypes.js

This will allow libs to build on Lucide by asking for an Icon from the lib

Export an Icon type for React

---

tags.json

You can't find bold icon if you search for "text" / "text editor" etc...
This should fix it.

Add missing tag "text" to bold icon

---

.github/workflows/font.yml
scripts/outline_svg.js

Fixes #354 
This PR creates a build artifact with fonts in several different weights. `fontcustom` doesn't support any kind of font weight combining that I see, so if you wanted to use multiple weights in the same project, you'd need to create a merged CSS file with the additional font faces you need.
The default weight (2) has no name suffix, while the others (1, 1.5, 2.5, and 3) use filenames that might match their expected css font-weights.
Shown: 200, 400 (the default), and 600 weight:
Artifact output: https://github.com/Billiam/lucide/suites/3139790111/artifacts/72098979

Build multiple font weights in action

---

packages/lucide-react/package.json

The library works perfectly with React 17 so it will allow users to not use `npm --legacy-peer-deps`

Allow to use with React 17

---

icons/archive.svg

Hello,  
I saw that the `archive` icon is breaking the "1 pixel padding within the canvas" rule and the "border radius of 2 pixels" rule.  
I made it a little smaller and added the border radius.  
This is how it looks now  
and this is how it looks at 100% scale

Refactor the archive icon

---

packages/lucide-react/scripts/buildTypes.js

- removed leftover references to `vue`
- removed redundant property declarations on `LucideProps`

Fix typescript declarations for lucide-react

---

packages/lucide-vue/README.md
packages/lucide-vue/nuxt.js

This PR adds support for the [@nuxt/components](https://github.com/nuxt/components) module's ability to automatically import Vue modules. As documented [here](https://github.com/nuxt/components#library-authors), a `nuxt.js` file tells Nuxt where the components are. 
In addition, this PR adds documentation on how to use this feature with Nuxt.

Support Nuxt auto-importing Vue components

---

icons/gem.svg

Co-authored-by: b0b90 <babersheikh@outlook.com>

add gem icon

---

packages/lucide-angular/package.json

I use windows and linux.
Befor, for compile lucide-angular  use linux only. Now I changed it for work in windows and linux .
I test it in windows and ubuntu.

Use 'angular build workflow' in Windows

---

icons/wrap-text.svg
tags.json

* Started with the "align-justify" icon
* Updated the second line to form a circular arc towards the third line, moved left slightly to finish the arcing path. Geometry: https://svg-path-visualizer.netlify.app/#M3%2012%20h15%20a3%203%200%201%201%200%206h-4
* Shortened the third line to form a gap between the third line and tip of the arc
* Layered a smaller version of "chevron left" on top of the tip of the arc (polyline)
Codepen: https://codepen.io/bduffs/pen/VwzGKxv

Add `wrap-text` icon

---

icons/pencil.svg

There was a line drawn all the way to the beginning of the path, which is what `z` already does anyway.
Refs: #129

chore: remove unnecessary bit from `pencil` icon

---

packages/lucide-preact/src/createPreactComponent.js
packages/lucide-react/src/createReactComponent.js

This will allow adding children to the SVG icons in React and Preact, thus allowing important a11y features like `<title>` tags, and of lesser importance also allowing custom additions to icons.
Both the Preact and React version place new children _before_ existing elements within the SVG. This is to comply with [this caveat found here on MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) to be backward compatible with SVG 1.1 (if this is a non-issue and other arguments can be made for adding new elements _after_ existing children, this can be reversed).
To avoid errors with destructuring non-existent Arrays, the Preact version uses `Preact.toChildArray()` (available in the Preact version required by the package) and the React version `children || []`.
Edit: I see this …

Allow children in React and Preact icons

---

icons/sidebar-close.svg
icons/sidebar-open.svg

This PR shrinks the size of the arrow in both the sidebar icons as they were looking too big and aligned the arrows 1px to the other side.

fix: shrink arrow size in sidebar icons

---

site/src/components/DocsMenu.tsx
site/src/components/HeadingTreeMenu.tsx
site/src/components/IconDetailOverlay.tsx
site/src/pages/icon/[iconName].tsx

I noticed a bunch of `console.log` calls on the website, which I assume were used at one point to test the website code but should probably not still be there.

fix: Remove console.log calls from site

---

site/src/pages/license.tsx

The license page has spaces missing where lines from the `LICENSE` file are joined.
I also changed the code a bit so the pipe symbol can be safely used in the license text :slightly_smiling_face:

fix: Spacing in License page

---

icons/frame.svg
tags.json

This PR adds a frame icon, as discussed in #531.
The chosen implementation is frame 1.

feat: add frame icon

---

icons/crop.svg

The `crop` icon has a few misaligned lines which I believe are probably not intentional. This pull request fixes these (assumed) errors, see (old vs. new):

Fix misaligned lines in `crop`

---

icons/credit-card.svg

This PR fixes guideline violations of the `credit-card` icon.

Fixes `credit-card`

---

icons/dollar-sign.svg

Fixes design guideline violations of `dollar-sign`.

Fixes `dollar-sign`

---

icons/chevrons-left-right.svg
icons/chevrons-right-left.svg
tags.json

* Icon name: chevrons-right-left + chevrons-left-right
* Use case: expanding and collapsing horizontally collapsible content (e.g. offcanvas or collapsible sidebar)
This pull request simply adds a horizontal variant of the already existing vertical double chevron icons:

chevrons-right-left + chevrons-left-right

---

icons/coins.svg

Fixes design guideline violations of `coins`:

Fixes `coins`

---

icons/milestone.svg
tags.json

* Icon name: milestone
* Use case: When representing GIT milestones or signs, signposts.
* _Screenshots_ of similar icons:

Added `milestone` icon

---

icons/contact.svg

The "class" property produces the following error when importing the icon in react using lucide-react and Typescript:
Warning: Invalid DOM property `class`. Did you mean `className`?

contact.svg - Remove "class" property to fix Typescript error

---

icons/calendar-check-2.svg
icons/calendar-check.svg
icons/calendar-days.svg
icons/calendar-minus.svg
icons/calendar-off.svg
icons/calendar-plus.svg
icons/calendar-range.svg
icons/calendar-x-2.svg
icons/calendar-x.svg
tags.json

* Icon name: extra calendar functions & operations
* Use cases:
* `calendar-plus`: creating new event, adding event to calendar
* `calendar-minus`: deleting or unsubscribing from event
* `calendar-x`:  removing or deleting event or marking a date as taken/busy
* `calendar-x-2`, `calendar-off`:  removing or deleting event
* `calendar-check`: subscribing to event, adding event to calendar, marking an event as complete or a date as taken etc
* `calendar-days`: using as an alternate style for calendar, representing a month or a list of dates.
* `calendar-range`: representing a date range, e.g. for daterange widgets.

Adds extra `calendar-*` icons

---

icons/armchair.svg
icons/bed-double.svg
icons/bed-single.svg
icons/bed.svg
icons/sofa.svg
tags.json

* Icon name: bed, single bed, double bed, sofa, armchair
* Use case: used in hotel, booking and smart home applications, to signify sleeping area, lounge, single & double bed etc.
* Originates from: #683

Adds `bed`, `armchair` & `sofa`

---

icons/cigarette-off.svg
icons/cigarette.svg
tags.json

* Icon name: `cigarette`, `cigarette-off`
* Use case: Marking smoking and especially no smoking environments.

Added `cigarette` & `cigarette-off`

---

icons/backpack.svg
icons/baggage-claim.svg
icons/luggage.svg
tags.json

* Icon name: backpack, baggage/luggage, baggage claim
* Use case: hotel/airport applications
* Originates from: https://github.com/lucide-icons/lucide/issues/683
(briefcase for comparison)

Adds `backpage`, `luggage`, `baggage-claim`

---

icons/clipboard-check.svg
icons/clipboard-list.svg
icons/clipboard-x.svg

Simplifies the source code of clipboard icons:
```diff
-  <path d="M15 2H9a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1z" />
+  <rect x="8" y="2" width="8" height="4" rx="1" ry="1" />
```

Optimizes `clipboard` icons

---

icons/list-end.svg
icons/list-music.svg
icons/list-start.svg
icons/list-video.svg
tags.json

* Icon name: playlist
* Use case:
* used for audio or video playback / playlists / queues
* `list-start` and `list-end` also useable when ordering lists (for the actions move to top/start & move to bottom/end)

Adds `list-start`, `list-end`, `list-music` & `list-video`

---

site/src/components/Header.tsx

Issue:
Fixes an accessibility issue where the anchor tags in the `Header` component, that link to the documentation of all the different frameworks, don't have a discernible name that accessibility tools can recognise.

Add Discernible Name to Inaccessible Links

---

README.md
docs/ILLUSTRATOR_GUIDE.md
packages/lucide-figma/src/views/Info.tsx
packages/lucide-static/README.md
packages/lucide-vue-next/README.md
packages/lucide-vue/README.md
scripts/generateChangelog.js
site/src/pages/packages/index.tsx

...in site code, scripts, documentation and readmes.

Replaces all occurences of `master` with `main`

---

icons/circle-dot.svg
icons/circle-ellipsis.svg
tags.json

* Icon name: circle ellipsis, circle dot
* Use case: https://github.com/feathericons/feather/issues/337, representing an uncompleted issue
* Originates from: https://github.com/lucide-icons/lucide/issues/119

Adds `circle-ellipsis` & `circle-dot`

---

.github/workflows/release.yml
packages/lucide-react-native/package.json

I believe that should fix the issues we're dealing with.
https://github.com/lucide-icons/lucide/runs/7116958776?check_suite_focus=true
Note: I was not able to get Yarn classic installed on my machine, so the changes related to lockfile are not included here. Sorry about that!

fix: fix lucide-react-native failing to publish

---

icons/mic-2.svg
icons/music-2.svg
icons/music-3.svg
icons/music-4.svg
tags.json

Add more music icons and another mic icon

---

icons/wand-2.svg
tags.json

* Icon name: magic wand
* Use case: application wizards
(the current wand icon is not quite suitable for this purpose as it more often represents selection)

Adds `wand-2` icon

---

icons/tag.svg
icons/tags.svg
tags.json

* Icon name: tags
* Use case: represents multiple tags or copying tags
* Also fixes the existing `tag` icon, making it pixel perfect

Fixes `tag` & adds `tags`

---

icons/mail-check.svg
icons/mail-minus.svg
icons/mail-open.svg
icons/mail-plus.svg
icons/mail-question.svg
icons/mail-search.svg
icons/mail-warning.svg
icons/mail-x.svg
icons/mails.svg
tags.json

* Icon name: mail-plus, mail-minus etc.
* Use cases:
* `mail-plus`: add/compose new mail
* `mail-minus`: remove mail
* `mail-check`: subscribed to mailing list or delivery success
* `mail-search`: search in mails
* `mails`: a list of emails, copy mail etc.
* `mail-open`: mail has been opened
* `mail-question`: unknown delivery status
* `mail-x`: delivery error or remove
* `mail-warning`: delivery error
* Also adjusts mail to be more in line with our design guidelines (no sharp corners unless necessary for clarity)

Adds further `mail` icons

---

icons/box-select.svg

Makes the dimensions of `box-select` in line with other square icons.

Fixes `box-select`

---

icons/medal.svg
icons/trophy.svg
tags.json

* Icon name: trophy & medal
* Use case: represents a winner, prize, award of achievement, as well as sports in general
* Originates from: #119 

Adds `trophy` & `medal` icons

---

icons/qr-code.svg

Updates `qr-code` to have the same dimensions as other square icons.

Fixes `qr-code`

---

icons/citrus.svg
tags.json

* Icon name: citrus
* Use case: cocktails or fruit in general, citrusy notes in smell/taste
* _Screenshots_ of similar icons:

Adds `citrus` icon

---

docs/packages/lucide-svelte.md

The additional props example previously had no props at all, this adds the color prop to solve that problem.
Resolves #782

Add color prop to "Additional Props" example

---

icons/arrow-up-down.svg
tags.json

There is already an `arrow-left-right` icon but not an `arrow-up-down` icon (this icon has just been turned around). You could use it as a reorder icon or as a mobile data icon.

Add `arrow-up-down` icon

---

docs/packages/lucide-vue-next.md

Currently the Vue 3 page tells you to go to `lucide-vue-next` for the Vue 2-compatible version

Fix typo in lucide-vue

---

CONTRIBUTING.md

Replace the ’How to Contribute to an Open Source Project on GitHub‘ guide link that's broken with a new link found on egghead.

Update broken guide link

---

icons/signal-zero.svg

Currently the icons `signal-zero` and `signal-low` are exactly the same.
Previously called out here https://github.com/lucide-icons/lucide/pull/428#issuecomment-1099289022 and confirmed by @ericfennis, the author of the original PR.
I've just manually edited `signal-zero` to remove the second bar.

Fix `signal-zero`

---

CONTRIBUTING.md

The build process uses import assertions which were added in Node 16.4. Updating the docs to reflect that since this bit me while contributing.
Example of import assertion
https://github.com/lucide-icons/lucide/blob/aa524c65a059ae802752c84f860b17cc3fa30977/scripts/render/processSvg.mjs#L5
[documentation for when import assertions were added in node](https://nodejs.org/api/esm.html#import-assertions)

Update CONTRIBUTING.md minimum node version

---

packages/lucide-vue-next/README.md

The title was a left-over for `lucide-vue-next`.

fixing the link title for Vue 2

---

docs/packages/lucide-vue-next.md

The generic icon component example for vue3 was missing an import for `computed` which has become an optional import with the composition api in vue3. I've fixed that and also refactored both examples to utilize the recently introduced `<script setup>` which increases the readability of components while reducing their lines of code.
The minimal usage example now looks like this:
``` html
<template>
<Camera
color="red"
:size="32"
/>
</template>
<script setup>
import { Camera } from 'lucide-vue-next';
</script>
```
Furthermore I've extended the example to proxy all properties (`size`, `color`, `strokeWidth` and `defaultClass`) to the specific icon components. Things like this are now possible with the example:
``` html
<template>
<div id="app">
<Icon name="Airplay" size="20" …
```

Docs: fix and extend the generic vue3 icon component example

---

package.json

For devs with Node + Corepack, but no pnpm, contribution will be seamless, as pnpm will be installed transparently in the background while running the first command.
https://pnpm.io/installation#using-corepack

Add packageManager to package.json to allow usage with Corepack

---

site/src/lib/fetchAllContributors.ts

Fixes #842
Please review carefully - I don't fully understand how this hash is used and whether there are any implications of changing it.

Don't use md4 in crypto.createHash

---

site/src/components/Package.tsx
site/src/pages/packages/index.tsx

Currently when running the site it will throw warnings that the `map()` needs a key.
This pr will fix this by adding the missing keys to the loop.

Add missing key to map loops for site

---

.github/workflows/ci.yml
.github/workflows/lucide-angular.yml
.github/workflows/lucide-preact.yml
.github/workflows/lucide-react-native.yml
.github/workflows/lucide-react.yml
.github/workflows/lucide-solid.yml
.github/workflows/lucide-static.yml
.github/workflows/lucide-svelte.yml
.github/workflows/lucide-vue-next.yml
.github/workflows/lucide-vue.yml
.github/workflows/lucide.yml
.github/workflows/release.yml

Fixed dependency warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout
```

Update GitHub Actions actions/checkout to v3

---

site/src/components/IconDetailOverlay.tsx
site/src/components/IconList.tsx
site/src/components/IconListItem.tsx
site/src/components/IconOverview.tsx
site/src/components/IconWrapper.tsx
site/src/lib/fetchAllContributors.ts
site/src/lib/icons.tsx
site/src/pages/index.tsx
site/src/types.ts

Reduces `__NEXT_DATA__` size on main page by 202694 bytes (~31%) by removing `content` property (it's now calculated based on `src` property) and removing `author.commit` data altogether.

Reduce __NEXT_DATA__ size by removing content and author.commit properties from IconEntity

---

README.md
docs/installation.md
docs/packages/lucide-angular.md
docs/packages/lucide-preact.md
docs/packages/lucide-react-native.md
docs/packages/lucide-react.md
docs/packages/lucide-static.md
docs/packages/lucide-svelte.md
docs/packages/lucide-vue.md
docs/packages/lucide.md
packages/lucide-angular/README.md
packages/lucide-preact/README.md
packages/lucide-react-native/README.md
packages/lucide-react/README.md
packages/lucide-solid/README.md
packages/lucide-static/README.md
packages/lucide-svelte/README.md
packages/lucide-vue-next/README.md
packages/lucide-vue/README.md
packages/lucide/README.md

GitHub adds Copy to clipboard button to all code snippets. By splitting npm and yarn specific snippets into two separate snippets we make it possible to copy the command dev is interested in in one click instead of manually selecting it and copying with Ctrl+C.

Split commands in documentation to make it possible to use Copy to clipboard icon

---

site/src/lib/fetchAllContributors.ts

Allows running marketing site in development for literally anyone else but @ericfennis :joy:

Don't hardcode GitHub username in fetchCommitsOfIcon, allow usage of GITHUB_TOKEN instead

---

site/src/components/Header.tsx

This makes it more clear there are more options than just the ones shown on the homepage.
Also removes the Laravel icon from the homepage,
since it is already part of the 3de party section.

Add show more link for packages on Homepage

---

pnpm-lock.yaml

Dedupes dependencies using [pnpm-deduplicate](https://www.npmjs.com/package/pnpm-deduplicate). Improves install speed, CI speed, GitHub Actions cache size.

Dedupe dependencies

---

packages/lucide-figma/src/api/fetchIcons.ts
packages/lucide-figma/src/components/IconButton/IconButton.scss
packages/lucide-figma/src/components/SearchInput/SearchInput.tsx
packages/lucide-figma/src/components/Skeleton/Skeleton.scss
packages/lucide-figma/src/components/Skeleton/Skeleton.tsx
packages/lucide-figma/src/interface/interface.tsx
packages/lucide-figma/src/views/Icons.tsx

Icons are now loaded from the cache instantly, and asynchronously updated. So no white screen anymore when starting up the plugin.

Improve Loading in figma plugin

---

.github/workflows/release.yml
packages/lucide-angular/package.json
pnpm-lock.yaml

We currently publish the whole angular project instead of the dist folder. Here is a screenshot from the last release build

Publish angular dist folder instead of project folder

---

packages/lucide-vue/package.json

I've opened this PR in relation to this [issue](https://github.com/lucide-icons/lucide/issues/888).
I've noticed that the Nuxt components integration works as expected until 0.84.0 (inclusive). It seems that the only thing that changed since then was the addition of the `files` property in `/packages/lucide-vue/package.json`, which only contained `dist`.
I've updated it to also contian `nuxt.js`, assuming this is what prevents `pnpm build` from removing it.
I would like to apologise if my approach is incorrect - my experience with front-end ecosystems is very limited, but I'm more than happy to learn.

add nuxt.js to `package.json` files

---

icons/battery-warning.json
icons/battery-warning.svg
tags.json

Can be useful when there's something wrong with the battery

add battery-warning icon

---

icons/globe-2.svg

The current icon has a lot of misaligned paths (circled in blue) as well as a weird sharp corner (red):

Fixes `globe-2` icon

---

site/src/components/Header.tsx

Should make it easier to distinguish react and react-native - shows a tiny hint when you hover over it.

add title attr for "Available for" icons on home

---

package.json
scripts/generate/generateIcons.mjs
scripts/helpers.mjs

This PR adds a very simple helper script to add SVG and JSON skeletons for multiple icons at once. Usage:
```sh
pnpm gi icon-name-1 icon-name-2
```

Adds generate icons script

---

icons/case-lower.json
icons/case-lower.svg
icons/case-sensitive.json
icons/case-sensitive.svg
icons/case-upper.json
icons/case-upper.svg
icons/replace-all.json
icons/replace-all.svg
icons/replace.json
icons/replace.svg
icons/space.json
icons/space.svg
icons/text-selection.json
icons/text-selection.svg
icons/whole-word.json
icons/whole-word.svg

As mentioned in another PR, I’m putting together a VS Code extension for Lucide product and file icons…
This PR is meant to cover the find/replace panel:
See also: _[codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)_

Add `find-replace` icons

---

icons/text.json
icons/text.svg

Keep existing icon, but match [`align-*`](https://lucide.dev/icons?search=align) icons, along with `list-selection` from [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html).

Add `text` icon

---

.github/workflows/pull-request.yml
site/src/components/SvgPreview/index.tsx
site/src/pages/api/gh-icon/[...data].tsx

Adds a backdrop, so you can see the difference that is introduced by the PR.

feat: added backdrop to gh-icon

---

icons/arrow-up-left-from-circle.json

This is causing the `pre-commit` hook to fail, because it was merged after the `coding` category was removed.

Fix `arrow-up-left-from-circle` metadata ❗

---

icons/moon-star.json
icons/moon-star.svg
icons/stars.json
icons/stars.svg

* Icon name: `stars`, `moon-star`
* Use case:
* `stars`: multimedia effects or filters, signifying nighttime or magic
* `moon-star`: an alternate for the regular moon icon to stand in for dark mode or nighttime.
* ![image](https://user-images.githubusercontent.com/17746067/233136100-2e3473c8-ab4e-406b-a26f-816ffc7c5f1b.png)
* ![image](https://user-images.githubusercontent.com/17746067/233136230-583461ea-68fe-49f3-9f82-a2daa3286284.png)

Added `stars` and `moon-star`

---

icons/arrow-big-down-dash.json
icons/arrow-big-down-dash.svg
icons/arrow-big-down.svg
icons/arrow-big-left-dash.json
icons/arrow-big-left-dash.svg
icons/arrow-big-left.json
icons/arrow-big-left.svg
icons/arrow-big-right-dash.json
icons/arrow-big-right-dash.svg
icons/arrow-big-right.svg
icons/arrow-big-up-dash.json
icons/arrow-big-up-dash.svg
icons/arrow-big-up.json
icons/arrow-big-up.svg
icons/chevron-up.json
icons/command.json
icons/option.json

Improve metadata for keys, and modify `arrow-big-*` icons to include `shift` key

---

icons/sidebar.json

Not sure what happened, but `sidebar.json` should have been deleted when replaced with `panel-left.json` in #1003… This is currently breaking the `pre-commit` hook!

Fix removal of `sidebar.json`❗️

---

icons/unplug.json

This broke the `pre-commit` hook again, because it was `merge`d after the `coding` category was removed.

Fix `unplug` metadata❗️

---

icons/group.json
icons/group.svg
icons/ungroup.json
icons/ungroup.svg

Alternatives:
Maybe the `selection` (dashed) version would be more appropriate…?

Add [`un`]`group` icons

---

packages/lucide-angular/package.json

Angular v16.0.0 has just been released two days ago. 🥳

[lucide-angular] Adds support for ng@16.x

---

icons/case-lower.svg
icons/case-sensitive.svg
icons/case-upper.svg
icons/space.svg
icons/whole-word.svg

Optimisations from #1023. Also related to #1041.
Plus following #1191, as mentioned in https://github.com/lucide-icons/lucide/pull/1191#issuecomment-1531675386 …
>  I think it hurts overall legibility.
Agreed that 2px radius might, but not so sure 1px harms legibility… What do you think @karsa-mistmere?

Optimise/refine `case-*`/`word`/`space` icons

---

icons/sparkle.json
icons/sparkle.svg

Added the `sparkle` icon, specifically for use in magic effects, UI for "new", and other related use cases.( For icon-request issue #1200 )

Add sparkle icon

---

packages/lucide-vue-next/scripts/buildTypes.mjs

According to the Discord thread. 
`strokeWidth` should be added to the types, because Vue is converting attributes from kebabcase to camelcase.

Add strokeWidth type for lucide-vue-next types

---

icons/play-square.json
icons/play-square.svg
icons/play.json

Generic ‘play video’ icon, especially since https://lucide.dev/icon/youtube will be [removed soon](https://github.com/lucide-icons/lucide/issues/94)…

Add `play-square` icon

---

icons/ticket.svg

Now has the same base dimensions as `credit-card`.

Increases `ticket` in size as per #1192

---

icons/move-down-left.json
icons/move-down-left.svg
icons/move-down-right.json
icons/move-down-right.svg
icons/move-down.json
icons/move-down.svg
icons/move-left.json
icons/move-left.svg
icons/move-right.json
icons/move-right.svg
icons/move-up-left.json
icons/move-up-left.svg
icons/move-up-right.json
icons/move-up-right.svg
icons/move-up.json
icons/move-up.svg

These icons are a second arrow variant that are a bit longer and consistent with the other move icons.
closes https://github.com/lucide-icons/lucide/issues/1226

Add alternative arrow icons

---

icons/spell-check-2.json
icons/spell-check-2.svg
icons/spell-check.json
icons/spell-check.svg

See #928… with credit to @jguddas
Explored:
Closes #928.

Add `spell-check` icons

---

icons/circle-dashed.json
icons/circle-dot-dashed.json
icons/circle-dot.json
icons/refresh-ccw-dot.json

Currently breaking the `pre-commit` hook, because the `coding` category was removed since these were originally created, but before they were merged.

Fix `circle-dot` icons metadata❗️

---

.gitignore
docs/.vitepress/api/categories/index.get.ts
docs/.vitepress/api/icon-nodes/index.get.ts
docs/.vitepress/api/icons/[iconName].get.ts
docs/.vitepress/api/tags/index.get.ts
docs/.vitepress/config.ts
docs/.vitepress/theme/components/icons/IconDetailOverlay.vue
docs/.vitepress/theme/components/icons/IconInfo.vue
docs/.vitepress/theme/components/icons/IconsCategoryOverview.vue
docs/.vitepress/theme/components/icons/IconsOverview.vue
docs/.vitepress/theme/components/icons/NoResults.vue
docs/.vitepress/theme/components/icons/SidebarIconCustomizer.vue
docs/.vitepress/theme/composables/useFetchCategories.ts
docs/.vitepress/theme/composables/useFetchTags.ts
docs/.vitepress/theme/composables/useIconStyle.ts
docs/.vitepress/theme/composables/useSearch.ts
docs/.vitepress/theme/composables/useSearchInput.ts
docs/icons/[name].md
docs/icons/[name].paths.ts
docs/icons/icons.data.ts
docs/package.json
scripts/writeIconDetails.mjs
scripts/writeIconNodes.mjs
scripts/writeIconRelatedIcons.mjs
scripts/writeReleaseMetadata.mjs

Changes:
- Add Max of related icons on icon detail pages, max is now 4 rows of icons on fullscreen (build is currently failing due to too much data).
- Increase icons overview page load by fetching icon details only when clicking on an icon.
- Increase icons overview page load by fetching tags and categories only when you start searching.
- Add horizontal scrolling to tags, some icons got a lot of tags, which currently breaks the layout.
- Add active state in icon Customizer, so you can quickly see if you touched the customizer controls.

Site improvements

---

icons/gem.json
icons/gem.svg

Explored `gem` variants, for reference…

Optimise `gem` icon/improve metadata

---

icons/arrows-up-from-line.json
icons/arrows-up-from-line.svg
icons/container.json
icons/container.svg

Shipping/Docker `container` like from [octicons](https://primer.style/design/foundations/icons/container-16). Reuses `cuboid` (brick) from #1142.
`arrows-up-from-line` commonly found on boxes to indicate package orientation. Often paired with a cracked glass icon to indicate fragile… See also `goblet-crack` in https://github.com/lucide-icons/lucide/pull/1374#issuecomment-1595896191.

Add shipping/`container` (Docker) icons

---

.vscode/svg.code-snippets

Helps with creation/optimisation of icons in VS Code, by adding some common basic shapes—with proper rounding—as snippets. Also to encourage best practices, like e.g using `path` vs [`poly`]`line`. This could be further expanded with other common elements, e.g `arrow`/`chevron` etc…
Related to #1224.

Add VS Code Lucide SVG snippets

---

icons/table-2.json
icons/table-properties.json
icons/table-properties.svg
icons/table.json
icons/table.svg

`table-properties` is property list (`.plist` file—see below…) But also can more generically represent a table of properties in general…

Optimise/add `table` icons/simplify metadata

---

packages/lucide-vue-next/scripts/buildTypes.mjs

Fix ts compilation and ide prompt stroke-width must be number.
This is a new request. I screwed up the previous one.

Fix lucide-vue-next stroke-width must be number bug

---

packages/lucide-angular/src/lib/lucide-icon.provider.ts

closes #1288
This PR adds a factory to the LUCIDE_ICONS injection token so that standalone components will be able to import LucideAngularModule without an unresolved dependency.

[lucide-angular] Improve standalone support

---

docs/guide/design/icon-design-guide.md

1. Icon design guideline no. 1 is one heading level deeper than it should be compared to others.
2. Examples for naming convention no. 3 are swapped

[docs] Fixes icon design guide heading levels + naming mix-up

---

packages/lucide-svelte/scripts/buildTypes.mjs

Closes #1507 
Build it and linked it to a small demo repo and it seems to work as before. 
Maybe we would need to change some documentation for some edge cases? @ericfennis 
On the same note: `SvgProps` is also [deprecated](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-getting-deprecation-warnings-for-sveltejsx--i-want-to-migrate-to-the-new-typings):
Just taking a quick look but couldn't find a replacement in `svelte/elements` so that's something we could add to this PR as well once we find it.

replaced SvelteComponentTyped with SvelteComponent

---

icons/russian-ruble.svg

I've simply optimised the `russian-ruble` icon, as it was made up of too many path parts.

Optimize russian-ruble.svg

---

icons/badge-percent.json
icons/percent-circle.json
icons/percent-circle.svg
icons/percent-diamond.json
icons/percent-diamond.svg
icons/percent-square.json
icons/percent-square.svg
icons/percent.json

Came across `percent-circle` in the wild the other day… Although others seem more appropriate representations of discount/price  tag…

Add `percent-*` (discount price tag) icons/improve metadata

---

icons/circle-slash-2.json
icons/circle-slash.json
icons/copy-slash.json
icons/slash.json
icons/slash.svg
icons/square-slash.json

Or, maybe it should match the slash/divide of https://lucide.dev/icon/equal-not …?

Add `slash` icon/improve [`*-`]`slash` metadata

---

packages/lucide-svelte/package.json

Closes #1536
SSR in Svelte Kit was not working due to a change in #1499. Thanks to @JanTrichter for the fix

Adjust export order Lucide Svelte

---

icons/ban.json

After merging #1241 we have a conflict with alias in `ban.json`. So this is removing this alias.

Remove conflicting alias: `slash`

---

docs/.vitepress/api/gh-icon/[...data].get.ts

- Icon with backdrop is now no longer broken in dark mode
- If you add an icon, let's say `folder-example`, it will show `folder` as the backdrop.
- If you open the `/gh-icon` route without a backdrop name, it will still work.

fix: gh-icon improvements

---

docs/guide/packages/lucide-react.md
packages/lucide-react/README.md

closes #1534
This PR adds documentation for using `lucide-react` with dynamic imports in NextJS. It also removes a warning that indicated that dynamic imports were experimental.

add info about dynamic imports to nextjs docs

---

.github/workflows/ci.yml
.github/workflows/lucide-angular.yml
.github/workflows/lucide-font.yml
.github/workflows/lucide-preact.yml
.github/workflows/lucide-react-native.yml
.github/workflows/lucide-react.yml
.github/workflows/lucide-solid.yml
.github/workflows/lucide-static.yml
.github/workflows/lucide-svelte.yml
.github/workflows/lucide-vue-next.yml
.github/workflows/lucide-vue.yml
.github/workflows/lucide.yml
.github/workflows/release.yml
packages/lucide-angular/package.json
packages/lucide-preact/package.json
packages/lucide-react-native/package.json
packages/lucide-react/package.json
packages/lucide-solid/package.json
packages/lucide-static/package.json
packages/lucide-svelte/package.json
packages/lucide-vue-next/package.json
packages/lucide-vue/package.json
packages/lucide/package.json

Cleaning up the workflow files by switching to the cache option from `actions/setup-node`.
And make sure we use Node 18 for all workflows since Node 16 is EOL.

Github Actions cleanup - Use setup node for pnpm cache

---

packages/lucide-vue-next/scripts/buildTypes.mjs

Closes #548
Declaring a component as `DefineComponent<Props>` can be correctly recognized by the IDE as a JSX element and provide autocompletion of props.

fix: jsx type for icons in vue 3

---

README.md

I have noticed one spelling mistake in **README** inside section "**Why choose Lucide over Feather icons**"
"**librairies**" should be "**libraries**"
Screenshot-

Update README.md - fix incorrect spelling.

---

icons/check-circle-2.svg
icons/check-circle.svg
icons/check-square-2.json
icons/check-square-2.svg
icons/check-square.svg
icons/check.svg

`check-square`[`-2`] was missing, plus these were inconsistent with other `check-`[`*`/`2`] icons, in that the `-2` variation is for when the check extends outside of it’s shape, as opposed to the original where it should be contained inside…

Optimise/add missing `check`[`-*`] icon/s

---

docs/.vitepress/api/gh-icon/[...data].get.ts
docs/.vitepress/lib/SvgPreview/Backdrop.tsx

Now it is red if the icon has changed and gray if the icon is a new icon in the same group.

feat: changed backdrop color for new icons in group to gray

---

docs/public/templates/illustrator_template.ai

- Remove all unnecessary Swatches, Strokes, Symbols and Graphic Styles
- Add useful Graphic Styles to easily toggle between shape/guide stroke and black stroke with the correct properties, which can be useful when designing more complex icons
- Add base shapes for reference, with correct rounding
- Changed example shape on Draw layer to existing arrow icon
- Fixed builtin grid by changing gridline every 72px with 1 subdivision (useless), to gridline every 1px. It might be preferable for some users to use the builtin grid rather than an actual Grid layer with guides, particularly as this can be toggled seperately with a hotkey (I _think_ certain preferences are saved with the document)
- All colours now match Lucide red (#F56565), also added as Swatch
- Convert guide layers to template …

Improve Adobe Illustrator template

---

icons/copy-check.json
icons/copy-check.svg
icons/copy-code.json
icons/copy-code.svg
icons/copy-down.json
icons/copy-down.svg
icons/copy-file-path.json
icons/copy-file-path.svg
icons/copy-image.json
icons/copy-image.svg
icons/copy-minus.json
icons/copy-minus.svg
icons/copy-plus.json
icons/copy-plus.svg
icons/copy-slash.json
icons/copy-slash.svg
icons/copy-text.json
icons/copy-text.svg
icons/copy-type.json
icons/copy-type.svg
icons/copy-x.json
icons/copy-x.svg
icons/copy.svg

* `copy-down` can be a generic clone icon, 'download all' or download*s*…
* `copy-file-path` is self-explanatory… Useful in editors.
* `copy-image` self-explanatory, but also can be photos/album/gallery…
* `copy-type` is copy with formatting (closely related to #1298)

Optimise `copy`[`-*`] icons/add `copy-down` (download all/generic clone) icon

---

icons/briefcase-plus.json
icons/briefcase-plus.svg
icons/chest.json
icons/chest.svg
icons/cross-square.json
icons/cross-square.svg
icons/cross.json
icons/lunch-box.json
icons/lunch-box.svg
icons/mailbox-flag.json
icons/mailbox-flag.svg
icons/mailbox.json
icons/mailbox.svg
icons/toolbox-2.json
icons/toolbox-2.svg
icons/toolbox.json
icons/toolbox.svg

Bunch of options… See column:
1. `briefcase-plus` (first aid kit)
2. `lunch-box`
3. `toolbox`
4. `chest`
5. … `mailbox`

Optimise/refine/add `*box`/`chest` icons

---

icons/cooking-pot.json
icons/cooking-pot.svg

A new icon with proposed changes from #1265 
This can be used to indicate, recipes, dinner (time) and kitchen. 
See design in #1265

Add cooking-pot icon

---

icons/a-arrow-down.json
icons/a-arrow-down.svg
icons/a-arrow-up.json
icons/a-arrow-up.svg
icons/a-large-small.json
icons/a-large-small.svg

Similar to what Microsoft Word does:
I haven't made any icons in a while so hopefully everything works properly with the new categories.

Add `font-size` icons

---

docs/.vitepress/theme/components/packages/PackageListItem.vue

closes #1750
Fixes package list item navigation error on lucide.dev as described in #1750

Fixes package list item 404 navigation error

---

packages/lucide-svelte/src/defaultAttributes.ts
packages/lucide-svelte/src/lucide-svelte.ts
packages/lucide-svelte/src/types.ts

Closes #1761 
`scripts/buildTypes.mjs` previously would add the `Icon` type into `lucide-svelte.d.ts` file during builds. This PR simply adds the type and exports it normally. I also noticed that the import path for `Attrs` didn't have an extension, so I added it there as well.

fix: Exports `Icon` type 

---

docs/guide/packages/lucide-svelte.md

Following the conversations in #1761 & #1585, this improves the docs around the areas of type definitions and import statements.
If there are any modifications you wish for me to carry out, please let me know. 🙂

docs: Add Lucide-Svelte icon import instructions and type definitions

---

packages/lucide-svelte/src/lucide-svelte.ts
packages/lucide-svelte/src/types.ts

closes #1776
For some reason not all types where exported in the main entry files

Export all types from lucide-svelte

---

packages/lucide-preact/rollup.config.mjs
packages/lucide-react/rollup.config.mjs
packages/lucide-vue-next/rollup.config.mjs
packages/lucide-vue/rollup.config.mjs

closes #1789 
Some UMD builds do not currently export icon aliases, this PR removes the `aliasesSupport` flag from rollup configs and turns the feature forcibly on by default.

Remove aliasesSupport flag from rollup.config.mjs

---

CONTRIBUTING.md
docs/.vitepress/sidebar.ts
docs/.vitepress/theme/components/base/Badge.vue
docs/.vitepress/theme/components/base/ButtonMenu.vue
docs/.vitepress/theme/components/base/CodeGroup.vue
docs/.vitepress/theme/components/base/FakeInput.vue
docs/.vitepress/theme/components/icons/CategoryListItem.vue
docs/.vitepress/theme/components/icons/CopyCodeButton.vue
docs/.vitepress/theme/components/icons/IconDetailOverlay.vue
docs/.vitepress/theme/components/icons/IconGrid.vue
docs/.vitepress/theme/components/icons/IconItem.vue
docs/.vitepress/theme/components/icons/IconsCategoryOverview.vue
docs/.vitepress/theme/composables/useSearchInput.ts
docs/guide/packages/lucide-react.md
docs/license.md
docs/nitro.config.ts
docs/package.json
pnpm-lock.yaml

- Site
General improvements site and site dependencies

Site improvements and update site dependencies

---

packages/lucide-react-native/src/createLucideIcon.ts
packages/lucide-react-native/src/lucide-react-native.ts

Closes #1791
Exporting all types in the main entry files so these types can be used externally.

Export all types `lucide-react-native`

---

docs/guide/packages/lucide-react-native.md

Change incorrect import path in Lucide `React Native -> One generic icon component` docs section

docs(react-native): fix generic icon import

---

scripts/generateChangedIconsCommentMarkup.mjs
scripts/helpers.mjs

Looks like the preview was not working in #1820. Looked into it, and the stripping whitespace regex was not working well. Replaced it with a minify function. tested it locally.

fix: icon preview comment

---

packages/lucide-svelte/scripts/exportTemplate.mjs

closes #1825 
Fixes incorrect return type in JSDoc Lucide svelte.

Update JSDoc Lucide Svelte

---

icons/clipboard-minus.json
icons/clipboard-minus.svg
icons/clipboard-plus.json
icons/clipboard-plus.svg
icons/shield-plus.json

Adding `clipboard-plus` and `clipboard-minus`.
- Adding something to the clipboard
- `clipboard-plus` could be used for medical use cases (not ideal), like doctor reports.
- Removing something from the clipboard

Add `clipboard-plus` and `clipboard-minus` icons

---

.vscode/svg.code-snippets

Following #1436, also reflect this fix in the VS Code snippets.

Add smaller dots `fill` fix to VS Code snippets

---

icons/shield-minus.svg
icons/shield-plus.svg

This PR updates `shield-plus` and `shield-minus` to better match other similar icons, e.g. `bell-plus`, `book-plus`, `file-plus`, `clipboard-plus` etc.

Fix plus/minus sign size in `shield-plus`/`shield-minus`

---

scripts/updateContributors.mjs

Stops us from getting the diff error.

fix: updateContributors adds trailing line to icon.json

---

icons/file-output.json
icons/file-output.svg

This aligns the design with the suggested change of folder-output in #1619

Update `file-output` icon

---

scripts/updateContributors.mjs

Prettier currently fails on updateContributors.mjs because of some missing end line commas, see https://github.com/lucide-icons/lucide/actions/runs/7875122496/job/21486295061?pr=1843

Fix: prettier fails on updateContributors.mjs 

---

icons/siren.svg

Fixes missing corner rounding in `siren`, as per #1865

Fix `siren` rounding

---

icons/concierge-bell.svg

#1896 and #1895 fixed some other guideline offenders, `concierge-bell` uses the same shape so it should also be fixed.

fix(icons/concierge-bell): Adds missing rounding from bottom part

---

docs/.vitepress/theme/components/icons/CategoryList.vue
docs/.vitepress/theme/components/icons/CategoryListItem.vue
docs/.vitepress/theme/components/icons/IconGrid.vue
docs/.vitepress/theme/components/icons/IconsCategory.vue
docs/.vitepress/theme/components/icons/IconsCategoryOverview.vue
docs/.vitepress/theme/components/icons/IconsOverview.vue
docs/.vitepress/theme/components/icons/NoResults.vue
docs/.vitepress/theme/composables/useActiveAnchor.ts
docs/.vitepress/theme/composables/useCategoryView.ts
docs/.vitepress/theme/composables/useScrollToCategory.ts
docs/.vitepress/theme/composables/useSearch.ts
docs/.vitepress/theme/style.css
docs/.vitepress/theme/utils/chunkArray.ts

Also closes #1724 
- Site update
- Improves scrolling with the use of virtual scrolling. Especially performant on mobile.
- Improves list rendering on the category page, when navigating to a category there is a bit of a lag.
- Improves floating marker position in the sidebar when scrolling through categories
- Fixes list rendering when resetting search.
- Sorting icons on category, closes #1724 
- Showing icon count per category in the sidebar when searching:

feat(site): adds virtual scrolling to icons grid and categories

---

docs/guide/packages/lucide-react-native.md
packages/lucide-react-native/README.md
packages/lucide-react-native/package.json
pnpm-lock.yaml

Add support for react-native-svg ^15.0.0

---

icons/play.svg

Fix https://github.com/lucide-icons/lucide/issues/1832
Lucide (black) vs Phosphor (red) now:

fix(icons): `play` icon uncentered

---

scripts/writeIconDetails.mjs
scripts/writeVercelOutput.mjs

Adds redirects for icon aliases
- Site update
When icons get renamed we add aliases for these. But currently on the site old names can't be resolved and results in a 404.
https://lucide.dev/icons/edit-3
https://lucide-36pmn4tea-lucide.vercel.app/icons/edit-3

Aliases redirect on site

---

icons/briefcase-business.json
icons/briefcase-business.svg
icons/briefcase-medical.json
icons/briefcase-medical.svg

Completes https://github.com/feathericons/feather/issues/1180 and related to #119
Adds two new briefcase variants, briefcase-medical as requested in https://github.com/feathericons/feather/issues/1180 and briefcase-business, which is a more portfolio-like variant.
The PR also pushes the existing briefcase icon 1px upwards for better vertical centering:
- briefcase-medical:
- first aid, help, support
- medical business
- briefcase-business
- business
- portfolio
- documents

feat(icons): add briefcase-medical & briefcase-business

---

packages/lucide-solid/rollup.config.mjs

closes https://github.com/lucide-icons/lucide/issues/1962
Our Solid export uses JS extensions, some frameworks, such as Tauri mistakenly use these sources as JS files, this PR updates our build flow so that these Solid exports are exported as JSX.

fix(packages/lucide-solid): use jsx extension for solid build

---

icons/ham.json
icons/ham.svg

A ham hock is often used to symbolize pork, we already have `drumstick` for chicken/poultry and `beef`.
Adds `ham` icon.
- to signify pork or cured meats
- to signify that a dish is not halal/kosher

feat(icons): added `ham` icon

---

packages/lucide-solid/package.json

In #1964, the build output was specified as .jsx, but it was not modified in package.json.

fix(lucide-solid): use jsx for exports too

---

packages/lucide/src/lucide.ts

closes #1975
Aliases aren't directly exported from `lucide`, this PR fixes this issue so that the package remains backwards compatible.

fix(packages/lucide): exports aliases from `lucide` package

---

icons/cpu.svg

CPU is missing the mandatory 1px rounding as dictated by our design guidelines.

fix(icons/cpu): add guideline compliant rounding to CPU center

---

icons/wallet.svg

fix(icons): added rounding to `wallet` icon

---

icons/pause.json
icons/pause.svg

fix(icons): added rounding to `pause` icon

---

icons/monitor-stop.svg

fix(icons): added rounding to `monitor-stop` icon

---

scripts/generateChangedIconsCommentMarkup.mjs

Added escaping of `
This is important to fix the broken pipeline!

fix: added escaping of quotes in generate comment markup script

---

icons/rotate-3d.json

Add `axis` tag to `rotate-3d`, bringing it in line with similar `axis-3d` and `move-3d`.

meta(icons): Add axis tag to rotate-3d

---

icons/coffee.json
icons/coffee.svg

Added roundness, manual operations where needed.

fix(icons): added rounding to `coffee` icon

---

icons/bot-off.json
icons/bot-off.svg

I'm currently developing an Obsidian plugin that has similar UI/UX to GitHub Copilot VSCode.
I need this `bot-off` icon for a Ribbon action item for this plugin, which shows the status of inline completions (i.e. enabled or disabled).
It will look something like this in VSCode:
The plugin uses the [`bot` icon](https://lucide.dev/icons/bot) for indicating that inline completions are enabled, and this `bot-off` icon will provide the counterpart for when they are disabled.
Or more generally speaking, this icon could be used in a status bar of any Web/native application which has some form of AI-powered features but allows its users to disable them for whatever the reasons.
As I mentioned earlier, I've made this icon based off the [`bot` icon](https://lucide.dev/icons/bot) - I believe this is …

Add bot-off icon

---

icons/diamond-minus.json
icons/diamond-minus.svg

The "Remove Keyframe" icon symbolizes precision and control in animation editing or video editing. With a simple click, it eliminates specific frames, enabling seamless adjustments and refining of animated sequences.
- removing keyframes in animation editing and video editing

feat(icons): add `diamond-minus`

---

icons/scale-3d.json

Add `axis` tag to `scale-3d`, bringing it in line with similar `axis-3d` and `move-3d`.

fix(icons): Add axis tag to scale-3d

---

packages/lucide-svelte/package.json
packages/lucide-svelte/src/Icon.svelte
pnpm-lock.yaml

fix(lucide-svelte): Revert shared package for `lucide-svelte`

---

docs/.vitepress/theme/components/base/Badge.vue
docs/.vitepress/theme/components/home/HomeHeroBefore.vue
docs/.vitepress/theme/components/icons/IconDetailOverlay.vue
docs/icons/[name].md

closes #2086
Links in badges that open externally would also be picked up by the Vue Router, resulting in a 404-page. 
Detection for external links is added in the Badge component, simultaneously adding the appropriate anchor tag attributes, as well as preventing the Vue Router from navigating.

fix: Prevent internal router from handling external links

---

icons/diamond-minus.json
icons/diamond-plus.json

An incorrect category was supplied in `diamond-plus` and `diamond-minus`, having been merged this now results in all pre commit hooks failing. 
> Icon 'diamond-minus' refers to the non-existing category 'shape'.
> Icon 'diamond-plus' refers to the non-existing category 'shape'.

fix(icons): fix incorrect category name for diamond-plus/minus

---

docs/.vitepress/api/data/index.get.ts

This PR adds a new data API endpoint the new Figma plugin can use to fetch the icon nodes, categories, aliases et cetera all at once.

feat(figma): add data API endpoint for new plugin

---

packages/lucide-svelte/src/Icon.svelte

fixes: #2114 
Removes export keyword.

fix(lucide-svelte): Remove export mergeClasses in svelte Icon

---

icons/paintbrush-vertical.json
icons/paintbrush-vertical.svg

fix(icons): added rounding to and renamed paintbrush-2

---

icons/pill-bottle.json
icons/pill-bottle.svg

closes #2173 
* To indicate sections related to prescription medications, over-the-counter drugs, or refills.
* For features like medication tracking, reminders, or a virtual medicine cabinet.
* To represent categories for pharmaceuticals, health supplements, and vitamins.
* To denote patient medication history or prescription details.
* To illustrate articles related to drug information, medication safety, or healthcare advice.
* For interfaces where healthcare professionals manage prescriptions and patient medication lists.
* To mark inventory sections for pharmaceuticals or to assist in prescription ordering processes.
* In promotional materials focused on medication adherence, vaccination programs, or safe drug use.
* As a visual cue for areas where patients can view or manage their …

feat(icons): added pill-bottle icon

---

icons/circle-slash.svg

Having <line> after <circle> allows to set `fill` as a background and line would still be visible
Currently, when you set `fill` property on svg, `<line>` won't be visible, as `<circle>` will cover it. Switching order allows to add background to the icon without losing `<line>`
Before:
After:

fix(icons): [circle-slash] Fix missing line when using `fill` as a background

---

docs/.vitepress/theme/components/icons/CopyCodeButton.vue

Add Copy component feature. It's very useful when you want to use the component name in your code other than the jsx code

Add copy component name

---

scripts/writeIconRelatedIcons.mjs

Running `prebuild:relatedIcons` results in an error:
```log
. prebuild:relatedIcons$ node ../scripts/writeIconRelatedIcons.mjs
│ node:internal/modules/esm/assert:88
│         throw new ERR_IMPORT_ATTRIBUTE_MISSING(url, 'type', validType);
│               ^
│ TypeError [ERR_IMPORT_ATTRIBUTE_MISSING]: Module "file:///Users/karsa/Projects/lucide/icons/a-arrow-up.json" needs an import attribute of "type: json"
│     at validateAttributes (node:internal/modules/esm/assert:88:15)
[1 lines collapsed]
│     at async ModuleLoader.load (node:internal/modules/esm/loader:555:7)
│     at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:436:45)
│     at async ModuleJob._link (node:internal/modules/esm/module_job:106:19) {
│2  code: 'ERR_IMPORT_ATTRIBUTE_MISSING'
│               ^
│ …
```

fix(scripts): fixes writeIconRelatedIcons.mjs

---

icons/pen-off.json

fix(icons): remove edit-2 alias from pen-off

---

scripts/writeVercelOutput.mjs

Aliases redirect was not working correctly when we changed to object definition for aliases.

fix(site): Aliases redirect

---

icons/house-plus.json
icons/house-plus.svg

feat(icons): added `house-plus` icon

---

categories/home.json

The icon `home` has been renamed and also needs to renamed here.

fix(categories): changed home category icon from `home` to `house`

---

icons/wifi-high.json
icons/wifi-high.svg
icons/wifi-low.json
icons/wifi-low.svg
icons/wifi-zero.json
icons/wifi-zero.svg

Adds a `wifi-zero`, `wifi-low` and `wifi-high` icon, which are all a variant of the `wifi` icon in lucide with a few bars removed. They are similar to the wifi strength indicators used in almost all operating systems, e.g. Android, iOS, Windows, etc.
These icons can be used to indicate specifically wifi signal strength in an operating systems UI / desktop environment. The `signal-*` icons often cannot be used for that, as they are usually associated with cellular signal and not wifi.
There are no alternative designs as the icons should be "parts" of the original and complete `wifi` icon.
I tried to keep the naming similar to the `signal-*` icons, so I used the `zero`, `low` and `high` suffixes.
I just copied the `wifi` icon and removed the paths that were not needed for the respective …

feat(icons): add wifi strength icons

---

docs/icons/[name].md

Fixes Svelte code examples that were showing `$PascalCase` instead of the Svelte component's tag
Issue stemmed from the fact that the `$` and `PascalCase` were not contiguous, and separated by HTML:
> Proposed fix is to add a a non-capturing group that matches zero or more occurrences of any sequence starting with <, followed by any characters that are not >, and ending with >; basically skipping over any HTML tags that might occur right after the `$` and before the `Pascal`.

fix(site): Fix svelte code examples

---

docs/.vitepress/theme/components/overrides/VPFooter.vue

This pull request addresses an issue with the footer links on website. Previously, both the `Github` and `Issues` links were pointing to the issue page (`/lucide/issues`). Now, the GitHub link directs to the correct repository.
Thanks!

fix(site): Correct GitHub link in the footer

---

icons/user-pen.json
icons/user-pen.svg
icons/user-round-pen.json
icons/user-round-pen.svg

1. **Profile Edit**
- **Description:** Indicating the option for users to edit their profile information.
- **Context:** Displayed on user profile pages or settings menus.
2. **Create Account**
- **Description:** Representing the action to create a new user account.
- **Context:** Used on registration forms or sign-up pages.
3. **Submit Feedback**
- **Description:** Signifying the feature for users to submit feedback or suggestions.
- **Context:** Found on feedback forms or customer support sections.
4. **Write a Review**
- **Description:** Allowing users to write and submit reviews or testimonials.
- **Context:** Displayed on product pages or review sections of a website.
5. **Edit Permissions**
- **Description:** Indicating the functionality to modify user permissions or roles.
- …

feat(icons): added user-pen and user-round-pen

---

icons/arrow-down-0-1.json
icons/arrow-down-1-0.json
icons/arrow-down-a-z.json
icons/arrow-down-narrow-wide.json
icons/arrow-down-wide-narrow.json
icons/arrow-down-z-a.json
icons/arrow-up-0-1.json
icons/arrow-up-1-0.json
icons/arrow-up-a-z.json
icons/arrow-up-narrow-wide.json
icons/arrow-up-wide-narrow.json
icons/arrow-up-z-a.json
icons/calendar-arrow-down.json
icons/calendar-arrow-down.svg
icons/calendar-arrow-up.json
icons/calendar-arrow-up.svg
icons/clock-arrow-down.json
icons/clock-arrow-down.svg
icons/clock-arrow-up.json
icons/clock-arrow-up.svg

feat(icons): added clock/calendar-arrow-up/down icons

---

icons/chart-column-increasing.svg

fix(icons): changed `chart-column-increasing` icon

---

icons/cloud-upload.json
icons/cloud-upload.svg

Use same arrow as everywhere else.

fix(icons): changed `cloud-upload` icon

---

icons/square-check-big.json
icons/square-check-big.svg

fix(icons): changed `square-check-big` icon

---

icons/cloud-download.svg

Update `cloud-download` to match the changes made in #2352

fix(icons): update `cloud-download` icon and close gaps

---

icons/microchip.json
icons/microchip.svg

We do not currently have an icon that could represent GPUs, this PR adds a `microchip` icon that could stand in for either GPUs or RAM.
- gpu
- ram
- microchip

feat(icons): adds microchip icon

---

icons/map-pin-house.json
icons/map-pin-house.svg

closes #1476
- Indicating a property location
- Marking a (home) address on a map application
- Representing a saved or favorite place in a navigation app
- Showing the location of a house in a local community map
- Displaying the location of a home on social media check-ins
- Marking the headquarters of a business
see #1476

feat(icons): add map-pin-house icon

---

icons/circle-ellipsis.json
icons/ellipsis-vertical.json
icons/ellipsis.json
icons/rectangle-ellipsis.json

Closes #2309 
Adds new tag to icons.
This PR adds a new tag `"more"` to some of the ellipsis icons.
The icons are: `circle-ellipsis`, `ellipsis-vertical`, `ellipsis`, `rectangle-ellipsis`

chore(icons): add tag to ellipsis icons

---

docs/.vitepress/theme/components/overrides/VPFooter.vue

Fixes a footer link typo.
Renamed "Github" to "GitHub".

chore(docs): fixed footer typo

---

.cspell/custom-words.txt
icons/table-of-contents.json
icons/table-of-contents.svg

closes #1859 (up for debate)
Adds a ToC icon.
- **Document Navigation**: An icon for a table of contents can be used in digital documents and eBooks to allow users to quickly navigate to different sections.
- **Websites and Blogs**: Use the icon on websites and blogs to help visitors jump to specific parts of long articles or pages.
- **PDF Viewers**: Integrate the icon into PDF viewers to offer a quick overview of the document's structure and enable easy access to different chapters.
- **Content Management Systems (CMS)**: Use the icon in CMS interfaces to assist users in organizing and accessing various content sections.
- **Educational Platforms**: Implement the icon in educational resources to help students and educators navigate through course materials and syllabi.
- **Software …

fix(icons): add table-of-contents icon

---

icons/bandage.json
icons/bandage.svg

closes #2324
Adds bandage icon as per #2324 #119 
- **First Aid Kits**: Indicating the presence of or access to first aid supplies.
- **Medical Apps**: Representing wound care, injury tracking, or health tips related to first aid.
- **Healthcare Websites**: Highlighting sections related to injury treatment, emergency care, or first aid instructions.
- **Safety Instructions**: Enhancing visual guidance in manuals or safety protocols.
- **Health & Wellness Blogs**: Accompanying articles on wound care, first aid tips, or injury prevention.
- **Pharmacy Services**: Indicating first aid products or services available at a pharmacy.
- **Hospital Signage**: Directing to first aid stations or emergency care units.
- **Sports Facilities**: Highlighting availability of first aid services or injury …

feat(icons): add bandage icon

---

icons/message-square-dashed.json
icons/message-square-dashed.svg

Use same dashes as `square-dashed`.

fix(icons): changed `message-square-dashed` icon

---

docs/guide/packages/lucide-angular.md

add standalone example for angular since it different with current behavior
I'm using Lucide with Angular and really love it. I'm using Angular 18 and this update should help standalone user understand how to use it for new standard

feat(docs): add standalone example for angular

---

icons/stethoscope.svg

fix(icons): fix stethoscope guideline violations

---

icons/leafy-green.json
icons/sprout.json
icons/sun.json
icons/tree-deciduous.json
icons/tree-palm.json
icons/tree-pine.json
icons/trees.json
icons/waves.json
icons/wind.json

Adds the sustainability category to some of the existing icons that are related to sustainability for easier discovery.

Add the sustainability category to some existing icons

---

icons/contact-round.json
icons/contact-round.svg
icons/contact.json
icons/contact.svg

Changed icon to be consistent with `square-user`.

fix(icons): changed `contact-*` icon

---

icons/octagon-minus.json
icons/octagon-minus.svg

Added new `octagon-minus` icon.
- Traffic symbol
- Restricted
- Forbidden access

feat(icons): added `octagon-minus` icon

---

icons/combine.json
icons/combine.svg

fix(icons): changed `combine` icon

---

icons/circle-stop.svg

fix(icons): changed `circle-stop` icon

---

docs/.vitepress/data/teamData.json

This PR fixes a misconfiguration in the Team section where `Eric Fennis's` Twitter link mistakenly pointed to his **GitHub** profile. 
**The correct Twitter link has now been added**, I Replaced the GitHub link with the correct Twitter link for `Eric Fennis's` name.

add(site): Eric Fennis's twitter link

---

packages/shared/package.json
packages/shared/tests/utils.spec.tsx
pnpm-lock.yaml

Checking that we don't have trailing spaces and such.
Related to #2498

tests(shared): added mergeClasses tests

---

docs/.vitepress/theme/components/base/Tooltip.vue

Fixes the tooltips on icons being cutoff. Closes #2412 . Increases the z-index to higher value so that they arent covered anymore by any obstructing things present on the website

fix(app): #2412 Fix tooltip being cut off

---

docs/.vitepress/theme/components/icons/CopyCodeButton.vue
docs/icons/[name].md
packages/shared/src/utils.ts

closes #2507 
The site uses `camelCase` and `startCase` from `lodash-es`, our packages don't. Let's fix this.

fix(site): use the same camel/pascal same conversion as when releasing packages

---

icons/align-center.svg
icons/align-justify.svg
icons/align-left.svg
icons/align-right.svg
icons/indent-decrease.svg
icons/indent-increase.svg
icons/list-ordered.svg
icons/list.svg

Replaced `<line/>` and `<polyline/>` elements with equivalent `<path/>`s using Lucide Studio's 'tidy' function

refactor(icons): optimised some `align`-, `indent`- and `list`-icons

---

icons/file-music.json
icons/file-music.svg

Moved corner line path to be more consistent with other file icons.

fix(icons): changed `file-music` icon

---

icons/hard-hat.json
icons/hard-hat.svg

fix(icons): changed `hard-hat` icon

---

docs/.vitepress/theme/components/home/HomeIconCustomizer.vue

This pull request addresses issue https://github.com/lucide-icons/lucide/issues/2566, which concerns the max-width property limiting the expansion of the card component. By adjusting the CSS, this update allows the card to expand fully without layout constraints, enhancing the display and usability of icons and related content.
CSS Adjustments for Card Expansion: Remove the max-width property on the card component to allow it to expand beyond previous limits.
Manually tested across different screen sizes to confirm that the card expands without layout issues.
Verified compatibility with other existing components

fix: #2566 expand card beyond max-width limit by adjusting CSS

---

icons/cloud-alert.json
icons/cloud-alert.svg

Adds new cloud-alert icon
My use case is for a "sync with cloud" feature, where I show the icon similar to how Google docs does it, when there is an issue with syncing to the cloud.
Another use case might be an extreme weather warning. 
I don't have alternative designs.

feat(icons): Add `cloud-alert` icon

---

docs/guide/packages/lucide-svelte.md

Svelte 5 specifics including removing the "ComponentType" typescript type as components are now static.  Also merged some imports into one-liners as we don't need to import each icon in a single line.
Added Svelte 5 specifics including how to make components with the now deprecated `ComponentType` typescript type.

[DOCS] Svelte 5 specifics for making components with the lucide-svelte package

---

icons/scale-3d.svg

fix(icons): changed `scale-3d` icon

---

icons/grid-2x2.json
icons/grid-2x2.svg

fix(metadata): added window related tags to `grid-2x2` icon metadata file

---

docs/guide/packages/lucide-static.md

this pr updates the docs to use valid icons in the static installation guide. the guide uses a `home` icon as demonstration, but such icon doesn't exist. i've replaced all references to `home` with `house`

docs(lucide-static): replace nonexistent icon references

---

icons/trophy.json

Adds `award`, `champion`, `celebration` and `victory` tags to the `trophy` icon

chore(metadata): add more tags to `trophy` icon

---

icons/grid-2x2-check.json
icons/grid-2x2-x.json
scripts/generateChangedIconsCommentMarkup.mjs
scripts/generateNextJSAliases.mjs

Fixes auto-formatting scripts.
Currently, the script [generateNextJSAliases.mjs](https://github.com/lucide-icons/lucide/pull/2712/commits/a79ac376e3350679c56c2cbbb9b50393c794edf8) is not matching the output the prettier and lining configuration. Which results in annoying changed files when running the pre-commit hook.

fix(scripts): Fix auto formatting script

---

docs/.vitepress/lib/codeExamples/createLabCodeExamples.ts

Fixes lab code examples for Vue and Svelte. It was always using "burger" as the value for the `iconNode` prop, rather than the name of the icon being viewed.
Vue:
Svelte:

fix(site): use lab icon name in vue and svelte examples

---

icons/triangle-dashed.json
icons/triangle-dashed.svg

adds triangle-dashed icon
I maintain an Obsidian drawing tool plugin, simple-sketch.
I'm going to allow users to draw dashed shapes, I can already add tool-buttons for circle and squares but not for triangles.

feat(icons): adds triangle-dashed icon

---

packages/lucide-react/package.json

fixes: #2730 
Probably fixes: #2729 
Adds `"type": "module"` in package json, so bundeler knows which export property it should use.

fix(lucide-react) Adds type module in package.json

---

icons/bolt.json

This PR fixes a typo in the `tags` for the `bolt` icon. The tag `"contruction"` was corrected to `"construction"`.

fix(bolt-icon): correct "contruction" typo in tags to "construction"

---

docs/guide/packages/lucide.md
packages/lucide/src/createElement.ts
packages/lucide/src/replaceElement.ts
packages/lucide/tests/__snapshots__/createElement.spec.ts.snap
packages/lucide/tests/createElement.spec.ts
packages/lucide/tests/helpers.ts
packages/lucide/tests/lucide.spec.ts

closes #2812 
closes #2802
This fixes the `createElement` function creating Lucide SVG Elements.
Also written some test for `createElement` function.

fix(lucide): Lucide create element function returning SVG Element

---

docs/.vitepress/theme/components/icons/IconInfo.vue
docs/.vitepress/theme/types.ts
docs/scripts/writeIconDetails.mjs

This pull request introduces a "Deprecated" badge that appears for icons flagged as deprecated in the `IconInfo.vue` component. This update improves the user interface by clearly indicating which icons are deprecated, helping users avoid using outdated assets.
- **Badge Component**: Added a `Badge` component to display the "Deprecated" label next to icons flagged as deprecated.
- **Conditional Badge Display**: Updated `IconInfo.vue` to conditionally show the deprecated badge if the icon has the` deprecated` property set to `true`.
- **Tooltip with Deprecation Details**: Included a tooltip that provides additional context on hover, displaying the reason for deprecation and the version in which the icon will be removed.
Manually tested the badge display on various icons, ensuring the …

feat(docs): Add deprecated badge for icons with deprecation status

---

.github/workflows/comment-icon-preview.yml
.github/workflows/pull-request-icon-preview.yml

After closing #2764
Icon PR comment is not working anymore, since it needs write access. The `GITHUB_TOKEN` with `on:  pull_request:` has only read access. With `workflow_run:` we also get write access to PRs and make sure it is secure.
This solution is based on a blog article form GH. https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

ci(pr-comment): Fix icon preview comment on PRs

---

icons/dam.json
icons/logs.json
icons/save-off.json
icons/signature.json

Last year I made some contributions to Lucide, but have since then changed by name and would like to see those changes reflected so the links on the lucide website go to my actual Github profile.

fix(metadata): name change reflected in contributions

---

icons/brackets.svg

fix(icons): changed `brackets` icon

---

packages/lucide-angular/package.json
packages/lucide-angular/src/aliases/index.ts

fix(packages/lucide-angular): restore exporting prefixed and suffixed icon names

---

icons/banknote-x.json
icons/banknote-x.svg

closes #2931 #1677 
Added new `banknote-x` icon.
Can be used in financial applications, payment platforms, or billing systems to indicate a failed, rejected, or canceled payment.
May also signify insufficient funds, transaction errors, or declined payments.

feat(icons): added `banknote-x` icon

---

docs/.vitepress/theme/components/packages/PackageList.data.ts

Resolves #2980
I changed packageData.name to pJson.name in PackageList.Data.ts as it was causing an error on the website in which users where being redirected to a 404 page.

fix(dev): point urls on packages page to correct page

---

.github/workflows/release.yml

> You can generate provenance statements for the packages you publish. This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.
https://docs.npmjs.com/generating-provenance-statements

feat(ci): added npm package provenance attestation

---

icons/toggle-left.json
icons/toggle-left.svg
icons/toggle-right.json
icons/toggle-right.svg

Increases the size of the `toggle` icons to help address issue #1192.

fix(icons): changed `toggle` icons

---

icons/palette.json
icons/palette.svg

Optimised some paths and pixel-aligned others

fix(icons): changed `palette` icon

---

icons/shredder.json

This PR fixes a formatting issue in `shredder.json` that has caused the Prettier check to fail on the last ~5 PRs.

fix(build): fix shredder formatting and duplicate contributors error

---

icons/non-binary.svg

I never saw #2607 got merged, I'm not super thrilled about the balance between the three icons (female and non-binary especially), but nonetheless, the asterisk as used by non-binary definitely should have been the same on we already use in `square-asterisk`.

fix(icons): rebase non-binary on square-asterisk

---

docs/.vitepress/config.ts

We are getting a lot of people creating icons who have not read the guidelines, we need to fix this somehow.
For now I say we are not ready for having Lucide Studio in the nav bar.

fix(site): remove studio link from navbar

---

docs/guide/design/icon-design-guide.md

docs(icon-design-guide): point people to lucide studio instead of svgo

---

icons/touchpad-off.json
icons/touchpad-off.svg

fix(icons): changed `touchpad-off` icon

---

icons/calendar-search.json
icons/file-search-2.json
icons/file-search.json
icons/folder-search-2.json
icons/folder-search.json
icons/mail-search.json
icons/package-search.json
icons/search-check.json
icons/search-code.json
icons/search-slash.json
icons/search-x.json
icons/search.json
icons/text-search.json
icons/user-round-search.json
icons/user-search.json

Added `lens` tag to icons with a magnifying glass.

chore(metadata): add `lens` tag to icons with magnifying glass

---

icons/axis-3d.json
icons/axis-3d.svg

Added rounding and made 3rd axis dashed.
<a title="Open lucide studio" target="_blank" href="https://studio.lucide.dev/edit?value=%3Cpath+d=%22m16+8.5-10+6%22+/%3E%3Cpath+d=%22M5.5+2v11.5a2+2+0+0+0+1+1.73l9+5.27%22+/%3E&name=box&dialog=false"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTYgOC41LTEwIDYiIC8+CiAgPHBhdGggZD0iTTUuNSAydjExLjVhMiAyIDAgMCAwIDEgMS43M2w5IDUuMjciIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

fix(icons): changed `axis-3d` icon

---

icons/chevrons-left-right-ellipsis.json
icons/chevrons-left-right-ellipsis.svg

Make the chevrons bigger to match `chevrons-left-right`.

fix(icons): changed `chevrons-left-right-ellipsis` icon

---

icons/square-code.json
icons/square-code.svg

Used `code` from `file-code-2`.

fix(icons): changed `square-code` icon

---

icons/wifi-cog.json
icons/wifi-cog.svg

Added new `wifi-cog` icon.
WiFi Settings Panels
To represent the user interface for configuring WiFi networks—SSID, passwords, frequency bands, etc.
Router / Modem Configuration UI
For dashboards where users can edit wireless network settings, channels, guest mode, etc.

feat(icons): added `wifi-cog` icon

---

icons/circle-arrow-left.svg
icons/circle-arrow-right.svg

This PR fixes a subtle rendering issue in the circle-arrow-left and circle-arrow-right Lucide icons.
Previously, the arrow shaft rendered before the arrowhead, leading to a visual gap at the junction when using `fill="green" stroke="white"` 
* The shaft `<path>` is now rendered after the arrowhead, allowing it to overlap and hide any anti-aliasing or stroke gap.
* No visual regressions expected; only layering order changed.
**Before**
**After (Fixed)**
---
**Before**
**After (Fixed)**
---

fix(icons): ensure shaft overlaps arrowhead in `circle-arrow-left` and `circle-arrow-right`

---

docs/.vitepress/lib/codeExamples/createCodeExamples.ts
docs/guide/packages/lucide-static.md

closes #3224 
Gave the `lucide-static` documentation page a bit of an overhaul and updated the icon font code example template to not use somewhat legacy webpack syntax.

docs(packages/lucide-static): update docs for better clarity

---

docs/guide/packages/lucide-svelte.md

The current example does not compile because `props` is not defined. This PR fixes that.

fix(docs): Icon Component Example for Svelte 5 does not compile

---

docs/.vitepress/theme/components/icons/IconItem.vue
docs/.vitepress/theme/components/icons/IconPreview.vue
docs/.vitepress/theme/components/icons/SidebarIconCustomizer.vue
docs/.vitepress/theme/composables/useIconStyle.ts

When customising icon size, colour and stroke width, downloaded icons do not reflect these changes, because the icon preview is broken. This PR fixes this issue, by passing through the correct icon component properties (`color`, not `stroke`; `strokeWidth`, not `stroke-width`; `size`, not `width` & `height`).
Also updated the customiser to allow up to 256×256px resolution, while limiting the displayed size.

fix(site): fixes icon style customiser

---

icons/messages-square.json

* Discussion - GitHub's discussions section uses this type of icon
* Interview - e.g. a category of content, alongside "article", "video", "podcast"
* Debate - in a similar vein to "interview"

chore(metadata): Added tags to `messages-square`

---

icons/building-2.svg

`building-2` also has ridiculously high optical volume, this PR fixes that, not sure about the invalid name. 🤔

fix(icons): changed `building-2` icon
