icons/grip-horizontal.svg, icons/grip-vertical.svg
Adds:
- Horizontal grip icon
- Vertical grip icon
=> feat: Add `grip` icons

LICENSE
Whoops, we need to update the license 😅
Let me know what you think. I think the ISC license is better than the MIT license, but that's just my opinion.
[Rendered `LICENSE` file](https://github.com/featherity/featherity/blob/refactor/license/LICENSE)
=> refactor: Update license

icons/snowflake.svg
=> feat: Add `snowflake` icon

icons/contact.svg
Hey :wave: was one project away of forking the repo myself. Thanks for doing this :)
Screenshot:
=> feat: Add `contact` icon

README.md
Update Discord Invite link and add Community section
=> docs: Update Discord invite

icons/copyright.svg
| Preview | Composition |
| ------- | ------------- |
| <img width="491" alt="Screenshot 2020-06-27 at 11 02 54" src="https://user-images.githubusercontent.com/62398724/85919782-68a46280-b866-11ea-85bd-84cb1b4922fc.png"> | <img width="492" alt="Screenshot 2020-06-27 at 11 03 10" src="https://user-images.githubusercontent.com/62398724/85919787-70640700-b866-11ea-8f8c-e430dcc6da78.png"> |
Related: https://github.com/feathericons/feather/issues/450
=> feat: Add `copyright` icon

icons/contrast.svg
Screenshot
Resolves https://github.com/feathericons/feather/issues/496
=> feat: Add `contrast` icon

icons/highlighter.svg
Screenshot
https://github.com/feathericons/feather/issues/227
=> feat: Add `highlighter` icon

icons/switch-camera.svg
Screenshot
https://github.com/feathericons/feather/issues/97
=> feat: Add `switch-camera` icon

icons/alarm-clock.svg
=> feat: Add `alarm-clock` icon

icons/coins.svg
Screenshot
https://github.com/feathericons/feather/issues/99
=> feat: Add `coins` icon

icons/library.svg
Related: https://github.com/feathericons/feather/pull/647, https://github.com/feathericons/feather/issues/643
=> feat: Add `library` icon

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/icon_request.md
I'm not sure that works though 😅
=> docs: Add labels to issue templates

icons/flashlight-off.svg, icons/flashlight.svg
=> feat: Add `flashlight` icons

.github/workflows/font.yml
Hi :wave:!
I created a workflow that compiles the Featherity font in various formats, including TTF, Woff2, SVG Spritesheet and CSS for web use 🤗 
I have tried it and there is no apparent problem 😄
---
https://github.com/featherity/featherity/issues/54
=> Workflow that will compile font files

icons/lightbulb.svg
Closes: [#150](https://github.com/feathericons/feather/issues/150)
Closes: [#661](https://github.com/feathericons/feather/issues/661)
100% ![Lamp](https://user-images.githubusercontent.com/11825403/92111308-6b827d00-edec-11ea-892e-9e6c6b66b4dc.png)
=> feat: Add lightbulb icon

icons/gauge.svg
Closes: [#12](https://github.com/feathericons/feather/issues/12)
Closes: [#408](https://github.com/feathericons/feather/issues/408)
Closes: [#934](https://github.com/feathericons/feather/issues/934)
100% ![gauge](https://user-images.githubusercontent.com/11825403/92124557-367f2600-edfe-11ea-9b96-5d46fb2ab6c6.png)
=> feat: add gauge icon

icons/bot.svg
Reference: https://github.com/feathericons/feather/issues/688
=> feat: Bot icon

icons/bluetooth-connected.svg, icons/bluetooth-off.svg, icons/bluetooth-searching.svg
Refactor bluetooth icon 
Added:
- bluetooth
- bluetooth-off
- bluetooth-connected
- bluetooth-searching
=> feat: add more bluetooth icons

icons/shirt.svg
Screenshot:
[Preview](https://github.com/featherity/featherity/pull/20/files?short_path=639344a#diff-639344af3b34774ca3f2f1b2bd3cb6cd)
=> feat: Add `shirt` icon

icons/calculator.svg
Closes: [#462](https://github.com/feathericons/feather/issues/462)
100%
=> Add calculator icon

icons/image-off.svg
For when images are not working.
100%
=> Add image-off icon

icons/mouse-pointer-2.svg, icons/move-diagonal-2.svg, icons/move-diagonal.svg, icons/move-horizontal.svg, icons/move-vertical.svg
=> feat: 'move-horizontal', 'move-vertical', 'move-diagonal', 'mouse-pointer-2'  

building.svg, tags.json
The  building icon. *(cf #78)*
=> Add building icon

.github/workflows/font.yml
I added a step that updates APT repositories before installing dependencies
=> FIX: 404 when installing dependencies using APT

.github/workflows/font.yml, scripts/outline_svg.js
I have changed part of the Workflow to run a Node script that solves the __peculiarities__ of SVGs files
=> Fix problems with SVGs

icons/indent.svg, icons/outdent.svg
=> Add indentation icons in/out

docs/ICON_DESIGN_GUIDE.md
This is just a proposal.
- Use modal verbs instead of "has"
- Use "icons" instead of "each icon"
- change some other things as well
=> Docs : Improve the design guide

site/package.json, site/src/components/ColorPicker.tsx, site/src/components/CustomizeIconContext.tsx, site/src/components/Header.tsx, site/src/components/IconCustomizerDrawer.tsx, site/src/components/IconDetailOverlay.tsx, site/src/components/IconList.tsx, site/src/components/IconWrapper.tsx, site/src/lib/icons.tsx, site/src/pages/index.tsx, site/yarn.lock
As discussed in #110 , this adds a knob for changing the color of the icons output by the website.  I also went ahead and added sliders for stroke-width and icon size similar to what is on the Feather Icons website.
=> Add customization options to the icon display and download

icons/album.svg
=> Add album icon

icons/menu.svg
Refactor the menu icon, I shorten the ends with 1px.
The top one is the refactored one.
=> Refactor Menu icon

icons/files.svg, tags.json
closes: #79
credits to @delnyn
=> Add files icon

icons/laptop-2.svg
For the icon request for the laptop I designed this one, bit we went with the one that is now in the library.
I think if you look at the icons widely used as an laptop, I think this one is also a welcome version to have in our library.
100% ![image](https://user-images.githubusercontent.com/11825403/98719446-10db4380-2390-11eb-9400-c16ca9d0aa43.png)
=> Add laptop-2 icon

icons/hand.svg
I was quite hard, but this is what came up with.
100% ![image](https://user-images.githubusercontent.com/11825403/99151648-f8736d80-269c-11eb-97e7-3d3199cd8f7f.png)
=> Add hand icon

icons/qr-code.svg
Closes: [#598](https://github.com/feathericons/feather/issues/598)
100%
=> Add qr-code icon

netlify.toml
=> Fix netlify build PRs

icons/locate-fixed.svg, icons/locate.svg, tags.json
Add 2 new icons, `locate` and `locate-fixed`
closes #156
=> feat: Add locate and locate-fixed icons

icons/crown.svg, tags.json
=> feat: Add crown icon

icons/layout-list.svg
To display a list with thumbnails.
100%
=> Add layout-list icon

icons/cross.svg
=> Add cross icon

icons/arrow-big-down.svg, icons/arrow-big-left.svg, icons/arrow-big-right.svg, icons/arrow-big-up.svg, tags.json
`arrow-big-right` ![image](https://user-images.githubusercontent.com/28541538/99154106-9f600580-26ad-11eb-955c-b394cfe9b8a6.png)
`arrow-big-left` ![image](https://user-images.githubusercontent.com/28541538/101170214-68429b80-363e-11eb-971c-8bf47426133c.png)
`arrow-big-up` ![image](https://user-images.githubusercontent.com/28541538/101170234-6ed11300-363e-11eb-83e5-5fd743274091.png)
`arrow-big-down` ![image](https://user-images.githubusercontent.com/28541538/101170265-7c869880-363e-11eb-9f46-63bfaa0c6cc0.png)
Part of #128;
=> Icons: Big arrows

icons/infinity.svg
Preview
Is it me, or the icon looks weird?
closes #172
=> Add infinity icon

icons/repeat-1.svg
=> Add repeat 1 icon

icons/alarm-check.svg, icons/alarm-minus.svg, icons/alarm-plus.svg
| `alarm-plus` | `alarm-minu` | `alarm-check` |
| --- | --- | --- |
| <img width="602" alt="CleanShot 2021-02-03 at 10 14 14@2x" src="https://user-images.githubusercontent.com/29014463/106699325-a7727600-6608-11eb-8ed5-a4c8c2d75789.png"> | <img width="602" alt="CleanShot 2021-02-03 at 10 14 10@2x" src="https://user-images.githubusercontent.com/29014463/106699338-ac372a00-6608-11eb-990e-9410bc78c20e.png"> | <img width="598" alt="CleanShot 2021-02-03 at 10 14 06@2x" src="https://user-images.githubusercontent.com/29014463/106699344-b0634780-6608-11eb-84ab-f36365b09726.png"> |
=> add alarm check, minus, plus icon

icons/asterisk.svg
| Preview |
| --- |
| <img width="340" alt="CleanShot 2021-02-02 at 21 09 36@2x" src="https://user-images.githubusercontent.com/29014463/106625188-72c8d500-659c-11eb-8573-286d43058c4e.png"> |
=> add asterisk icon

icons/sigma.svg
| Preview |
| --- |
| <img width="658" alt="CleanShot 2021-02-03 at 09 52 10@2x" src="https://user-images.githubusercontent.com/29014463/106698156-434eb280-6606-11eb-910e-42d594a8c4cb.png"> |
=> add sigma icon

icons/shield-alert.svg, icons/shield-check.svg, icons/shield-close.svg
| `shield-check` | `shield-alert` | `shield-close` |
| --- | --- | --- |
| <img width="459" alt="CleanShot 2021-02-03 at 22 41 28@2x" src="https://user-images.githubusercontent.com/29014463/106783614-7b3f0f80-6671-11eb-9740-b60c527c3207.png"> | <img width="452" alt="CleanShot 2021-02-03 at 22 41 24@2x" src="https://user-images.githubusercontent.com/29014463/106783673-88f49500-6671-11eb-9d8b-d9c420fd4b98.png"> | <img width="447" alt="CleanShot 2021-02-03 at 22 41 20@2x" src="https://user-images.githubusercontent.com/29014463/106783683-8d20b280-6671-11eb-9990-6fdce560a2d9.png"> |
=> add shield alert, check & close icon

icons/bell-minus.svg, icons/bell-plus.svg
| `bulb-plus` | `blub-minus` |
| --- | --- |
| <img width="579" alt="CleanShot 2021-02-07 at 22 12 58@2x" src="https://user-images.githubusercontent.com/29014463/107153083-a7b89b80-6991-11eb-854a-18f8c0c39afa.png"> | <img width="578" alt="CleanShot 2021-02-07 at 22 10 51@2x" src="https://user-images.githubusercontent.com/29014463/107153072-9ec7ca00-6991-11eb-945f-12999ac4a849.png"> |
=> add bell plus & minus icon

icons/option.svg
| Preview |
| --- |
| <img width="280" alt="CleanShot 2021-02-09 at 18 32 21@2x" src="https://user-images.githubusercontent.com/29014463/107367313-28e46f80-6b05-11eb-8279-4b0df28a179e.png"> |
_For mac users this icon will make sense_
=> add option icon

icons/inspect.svg
| Preview |
| --- |
| <img width="426" alt="CleanShot 2021-02-05 at 10 00 53@2x" src="https://user-images.githubusercontent.com/29014463/106990033-7aa19880-6799-11eb-8f08-af3a23092965.png"> |
=> add inspect icon

icons/pencil.svg
=> Add pencil icon

icons/regex.svg
| Preview |
| --- |
| <img width="600" alt="CleanShot 2021-02-06 at 14 22 37@2x" src="https://user-images.githubusercontent.com/29014463/107113801-499f9180-6887-11eb-941d-d307e25ee47f.png"> |
=> add regex icon

icons/binary.svg
| Preview |
| --- |
| <img width="393" alt="CleanShot 2021-02-03 at 22 19 50@2x" src="https://user-images.githubusercontent.com/29014463/106780790-5c8b4980-666e-11eb-84c8-f12febc16dbf.png"> |
=> add binary icon

icons/history.svg
Closes [#291](https://github.com/feathericons/feather/issues/291)
=> Add history icon

icons/tv-2.svg
=> Add tv-2 icon

icons/radio-receiver.svg
=> Add radio receiver

icons/languages.svg
| Preview |
| --- |
| <img width="529" alt="CleanShot 2021-02-23 at 20 52 28@2x" src="https://user-images.githubusercontent.com/29014463/108865571-6377fd00-7619-11eb-9dae-a773b849a3ff.png"> |
=> maintain 1px border spacing in languages icon

icons/clipboard-list.svg
| Preview |
| --- |
| <img width="323" alt="CleanShot 2021-02-26 at 10 26 31@2x" src="https://user-images.githubusercontent.com/29014463/109257177-97237480-781d-11eb-824a-4b4f608401f8.png"> |
=> add clipboard-list icon

icons/loader-2.svg
| Preview |
| --- |
| <img width="571" alt="CleanShot 2021-02-17 at 22 43 05@2x" src="https://user-images.githubusercontent.com/29014463/108241227-9df11e00-7171-11eb-925c-3c7a23f953fb.png"> |
=> Add loader-2 icon

tags.json
Closes #250 
If you have suggestion, please post it in this PR.
=> Add more tags

icons/redo.svg, icons/undo.svg
Refactored the undo and redo icons based on the current rotate icons
100% ![image](https://user-images.githubusercontent.com/11825403/110355143-34aa4f80-8039-11eb-8af2-e200fa44ba73.png)
=> Refactor redo & undo

icons/mouse-pointer-click.svg
| Preview |
| --- |
| <img width="577" alt="CleanShot 2021-02-07 at 22 03 12@2x" src="https://user-images.githubusercontent.com/29014463/107152930-d08c6100-6990-11eb-89d9-730130f92dca.png"> |
=> add mouse-pointer-click icon

icons/file-input.svg, icons/file-output.svg
=> file-input and file-output

icons/thermometer-snowflake.svg, icons/thermometer-sun.svg
=> Add new thermometer icons

.gitignore, package.json, scripts/buildDts.js
For use in typescript project like angular.
=> Generate index.d.ts when build

icons/star-half.svg
| Preview |
| --- |
| <img width="752" alt="CleanShot 2021-01-27 at 21 18 52@2x" src="https://user-images.githubusercontent.com/29014463/106016578-9c3db880-60e5-11eb-91bb-20b46fec4e26.png"> |
=> Add star-half icon

packages/lucide-react/package.json, packages/lucide-vue/package.json, packages/lucide/package.json
=> Add rm to yarn clean command

icons/power-off.svg
| Preview |
| --- |
| <img width="572" alt="CleanShot 2021-02-03 at 22 37 15@2x" src="https://user-images.githubusercontent.com/29014463/106782993-d3c1dd00-6670-11eb-8865-df4372481baa.png"> |
=> add power-off icon

package.json, packages/lucide-angular/.gitignore, packages/lucide-angular/angular.json, packages/lucide-angular/package.json, packages/lucide-angular/projects/lucide-angular/README.md, packages/lucide-angular/projects/lucide-angular/default-attributes.ts, packages/lucide-angular/projects/lucide-angular/icons-index.ts, packages/lucide-angular/projects/lucide-angular/icons/package.json, packages/lucide-angular/projects/lucide-angular/karma.conf.js, packages/lucide-angular/projects/lucide-angular/lib-index.ts, packages/lucide-angular/projects/lucide-angular/lucide.ts, packages/lucide-angular/projects/lucide-angular/ng-package.json, packages/lucide-angular/projects/lucide-angular/package.json, packages/lucide-angular/projects/lucide-angular/src/lib/icons.provider.ts, packages/lucide-angular/projects/lucide-angular/src/lib/lucide-angular.component.spec.ts, packages/lucide-angular/projects/lucide-angular/src/lib/lucide-angular.component.ts, packages/lucide-angular/projects/lucide-angular/src/lib/lucide-angular.module.ts, packages/lucide-angular/projects/lucide-angular/src/test.ts, packages/lucide-angular/projects/lucide-angular/tsconfig.lib.json, packages/lucide-angular/projects/lucide-angular/tsconfig.lib.prod.json, packages/lucide-angular/projects/lucide-angular/tsconfig.spec.json, packages/lucide-angular/projects/lucide-angular/tslint.json, packages/lucide-angular/scripts/buildIconsIndex.js, packages/lucide-angular/scripts/exportTemplate.js, packages/lucide-angular/tsconfig.json, packages/lucide-angular/tslint.json
All changes are in
* Folder `<PROJECT>/packages/lucide-angular`.
* File `Package.json` in root of project for fix conflict build by yarn workspace.
And please change this steps by admin:
1) Add to git action and publish npm package
* For build `yarn workspace lucide-angular build`
* For test `yarn workspace lucide-angular test:headless`
* For update version change file `<PROJECT>/packages/lucide-angular/projects/lucide-angular/package.json`
* For build package of npm use folder `<PROJECT>/packages/lucide-angular/dist/lucide-angular`
2) I create README.md for angular and describe `How to use` . Please add angular section to README.md of root project
I build and test this package in my project.
=> Add lucide-angular

icons/code-2.svg
closes #93 
Credits to @johnletey
=> Add code-2 icon

README.md, package.json, packages/lucide-angular/.gitignore, packages/lucide-angular/angular.json, packages/lucide-angular/package.json, packages/lucide-angular/projects/lucide-angular/README.md, packages/lucide-angular/projects/lucide-angular/default-attributes.ts, packages/lucide-angular/projects/lucide-angular/icons-index.ts, packages/lucide-angular/projects/lucide-angular/icons/package.json, packages/lucide-angular/projects/lucide-angular/karma.conf.js, packages/lucide-angular/projects/lucide-angular/lib-index.ts, packages/lucide-angular/projects/lucide-angular/lucide.ts, packages/lucide-angular/projects/lucide-angular/ng-package.json, packages/lucide-angular/projects/lucide-angular/package.json, packages/lucide-angular/projects/lucide-angular/src/lib/icons.provider.ts, packages/lucide-angular/projects/lucide-angular/src/lib/lucide-angular.component.spec.ts, packages/lucide-angular/projects/lucide-angular/src/lib/lucide-angular.component.ts, packages/lucide-angular/projects/lucide-angular/src/lib/lucide-angular.module.ts, packages/lucide-angular/projects/lucide-angular/src/test.ts, packages/lucide-angular/projects/lucide-angular/tsconfig.lib.json, packages/lucide-angular/projects/lucide-angular/tsconfig.lib.prod.json, packages/lucide-angular/projects/lucide-angular/tsconfig.spec.json, packages/lucide-angular/projects/lucide-angular/tslint.json, packages/lucide-angular/scripts/buildIconsIndex.js, packages/lucide-angular/scripts/exportTemplate.js, packages/lucide-angular/tsconfig.json, packages/lucide-angular/tslint.json
After merge `buid d.ts`, `lucide-angular` is not availabe.
I request it again.
=> Add lucide-angular again!

icons/bug.svg
100% ![bug](https://user-images.githubusercontent.com/11825403/110354434-6ff84e80-8038-11eb-8ae1-e5bba03365a7.png)
=> Add bug icon

README.md
Link of `Web` and `Angular` in `README.md ` in root is broken.
=> Fix link of README

icons/ghost.svg
| Preview |
| --- |
| <img width="492" alt="CleanShot 2021-04-14 at 09 27 00@2x" src="https://user-images.githubusercontent.com/29014463/114652497-9a0df200-9d03-11eb-96d1-2dbe8a586480.png"> |
=> add ghost icon

.github/workflows/release.yml
I'm not sure it will work.
Please review.
=> Add workflow for release lucide-angular

icons/ticket.svg
| Preview |
| --- |
| <img width="683" alt="CleanShot 2021-02-07 at 22 38 17@2x" src="https://user-images.githubusercontent.com/29014463/107153793-5ca08780-6995-11eb-8cf9-99dca31ced7f.png"> |
=> add ticket icon

icons/scale.svg
| Preview |
| --- |
| <img width="569" alt="CleanShot 2021-02-03 at 22 24 49@2x" src="https://user-images.githubusercontent.com/29014463/106782248-f30c3a80-666f-11eb-9e56-fd056168e69c.png"> |
=> add scale icon

icons/circle-slashed.svg, icons/zero-config.svg
| Preview |
| --- |
| <img width="459" alt="CleanShot 2021-04-14 at 13 36 55@2x" src="https://user-images.githubusercontent.com/29014463/114676505-f9312e00-9d26-11eb-8543-9f9313787ee4.png"> |
=> add zero-config icon

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/icon_request.md, .github/PULL_REQUEST_TEMPLATE/new-icon.md
Also uses proper labels for the issue templates.
I think the bug report issue template should be improved, btw.
=> Add pull request template for new icons

icons/accessibility.svg, icons/person-standing.svg
| Preview |
| --- |
| <img width="595" alt="CleanShot 2021-02-03 at 10 14 01@2x" src="https://user-images.githubusercontent.com/29014463/106699378-c4a74480-6608-11eb-9f78-13893b24612c.png"> |
=> add accessibility icon

icons/pause-octagon.svg
| Preview |
| --- |
| <img width="282" alt="CleanShot 2021-05-01 at 15 44 39@2x" src="https://user-images.githubusercontent.com/29014463/116779540-6ddcca00-aa94-11eb-804f-acb47bb10319.png"> |
=> add pause octagon icon

icons/skull.svg
=> Add skull icon

icons/clipboard-check.svg
| Preview |
| --- |
| <img width="268" alt="CleanShot 2021-05-15 at 09 42 16@2x" src="https://user-images.githubusercontent.com/29014463/118347599-29f0c700-b562-11eb-84ec-0da7639d98e8.png"> |
=> add clipboard check icon

icons/clipboard-x.svg
| Preview |
| --- |
| <img width="431" alt="CleanShot 2021-05-15 at 09 49 57@2x" src="https://user-images.githubusercontent.com/29014463/118347730-1134e100-b563-11eb-88d2-588195c8b575.png"> |
=> add clipboard-x icon

tags.json
=> Update tags for the website

icons/vibrate.svg
=> Add vibrate icon

icons/clipboard-copy.svg
| Preview |
| --- |
| <img width="328" alt="CleanShot 2021-02-26 at 10 26 34@2x" src="https://user-images.githubusercontent.com/29014463/109257194-a1457300-781d-11eb-9837-4b59f3544f98.png"> |
=> add clipboard-copy icon

icons/bell-ring.svg
=> Add bell-ring icon

icons/chevrons-down-up.svg, tags.json
Related issue: #343
Complements : #238
=> Add `chevrons-down-up` icons

tags.json
Issue: #339 Alias for icon `send`
=> Add alias "submit" and "wait"

site/src/components/Header.tsx
=> Rename zip filename site

icons/smartphone-charging.svg
| Preview |
| --- |
| <img width="359" alt="CleanShot 2021-05-09 at 17 33 21@2x" src="https://user-images.githubusercontent.com/29014463/117571550-ae6bc180-b0ec-11eb-9bb1-3c5c4b582d07.png"> |
=> add smartphone-charging icon

icons/currency.svg, tags.json
=> add currency icon

icons/rocking-chair.svg, tags.json
Co-authored-by: b0b90 <babersheikh@outlook.com>
=> add rocking chair icon

icons/megaphone.svg
| Preview |
| --- |
| <img width="528" alt="CleanShot 2021-02-06 at 14 15 24@2x" src="https://user-images.githubusercontent.com/29014463/107113814-60de7f00-6887-11eb-97c3-0a794d9f005c.png"> |
=> Add megaphone icon

icons/landmark.svg, tags.json
This adds a landmark / bank icon. The style of the icon was discussed in #358 .
**Preview**
Fixes #358
=> add landmark icon

icons/alarm-clock-off.svg
| Preview |
| --- |
| <img width="694" alt="CleanShot 2021-02-03 at 13 18 32@2x" src="https://user-images.githubusercontent.com/29014463/106715102-b6662200-6622-11eb-85ea-3361220e9470.png"> |
=> add alarm-clock-off icon

icons/sort-asc.svg, icons/sort-desc.svg
closes #361 
Switched the stack.
=> Fix sort icons, Switch asc desc stack

icons/list-minus.svg, icons/list-plus.svg, icons/list-x.svg, tags.json
=> Add list-plus icon

.github/workflows/release.yml
Fixes #414, Also we are in october so have this repository participated in Hacktoberfest?
If so then I would love to have `hacktoberfest-accepted` label in this PR. Other then that you can add `hacktoberfest` tag to your repository to participate in it.
=> Fix flutter package generation

packages/lucide-angular/.gitignore, packages/lucide-angular/package.json
I test in angular v11, v12 and v13.
#427
=> Support Angular version 11 or higher

packages/lucide/scripts/buildTypes.js
Some refactoring when build typing for of lucide
=> Refactoring

icons/timer-off.svg
| Preview |
| --- |
| <img width="409" alt="CleanShot 2021-05-01 at 15 50 24@2x" src="https://user-images.githubusercontent.com/29014463/116779691-6964e100-aa95-11eb-8dbb-23240848c5e0.png"> |
=> add timer off icon

icons/arrow-left-right.svg, tags.json
=> feat: add `arrow-left-right` icon

icons/clock-1.svg, icons/clock-10.svg, icons/clock-11.svg, icons/clock-12.svg, icons/clock-2.svg, icons/clock-3.svg, icons/clock-4.svg, icons/clock-5.svg, icons/clock-6.svg, icons/clock-7.svg, icons/clock-8.svg, icons/clock-9.svg
https://user-images.githubusercontent.com/5426427/143689259-76f54ca1-ca12-4077-9515-f05dc1e3221c.mov
=> feat: Add `clock-*` icons

icons/scan-line.svg, icons/scan.svg
=> feat: add `scan`, `scan-line` icons

packages/lucide/src/replaceElement.js, packages/lucide/tests/lucide.spec.js
=> Fix inheriting attrs

site/babel.config.js, site/next-env.d.ts, site/next.config.js, site/package.json, site/src/components/Header.tsx, site/src/components/IconList.tsx, site/src/components/IconListItem.tsx, site/tsconfig.json, site/yarn.lock
- Fix for the overlapping icon names over other icons
- Added Svelte icon
- Updated to next 12.1
=> Minor fixes lucide.dev

icons/locate-off.svg, tags.json
=> Add LocateOff icon

packages/lucide-react/README.md
Hello,
Great job with this library. Very excited! <3
I initially intended a minor change of strong -> substantially in the react readme, but I then did a general edit pass on the readme as well. If you don't like the proposed changes, I can go back to just changing the single word (or a maintainer can).
Thank you! :D
=> Minor edits to react readme.

icons/keyboard.svg, tags.json
=> Add keyboard icon

icons/baseline.svg, tags.json
=> Add Baseline icon

icons/rocket.svg, tags.json
=> Add rocket icon

icons/dice-1.svg, icons/dice-2.svg, icons/dice-3.svg, icons/dice-4.svg, icons/dice-5.svg, icons/dice-6.svg, tags.json
| Preview |
| --- |
| <img width="407" alt="CleanShot 2022-03-10 at 23 18 45@2x" src="https://user-images.githubusercontent.com/29014463/157724271-5de45bbe-5cda-4a6a-a7ac-1abb431b519a.png"> |
Reference: https://github.com/lucide-icons/lucide/discussions/463
=> feat: add dice icons

icons/git-fork.svg, tags.json
=> Add git-fork icon

packages/lucide-vue-next/scripts/buildTypes.js
=> Fix types lucide-vue-next

icons/eraser.svg, tags.json
- **Name of the icon** : eraser
- **Tags (alternative names for this icon)** (add them in tags.json) :  "pencil", "drawing", "undo", "delete", "clear"
- **What is the purpose of this icon?** :Eraser tool for graphical interfaces
- **100% scale preview** : _see below_
- **Have you considered alternative possibilities** for its naming or design? : not really
=> Add eraser icon

icons/flag-off.svg, tags.json
* Icon name: flag-off
* Use case: Removing the flagged state from a previously flagged item
* _Screenshots_ of similar icons: 
Proposed icon:
=> flag-off / unflag

icons/map-pin.svg
=> Fixes `map-pin`

icons/voicemail.svg
=> Fixes `voicemail`

icons/trending-down.svg, icons/trending-up.svg
=> Fixes `trending-down` & `trending-up`

icons/coffee.svg
Fixes design guideline violations of `coffee`
=> Fixes `coffee`

tags.json
=> Add tags for icon `grip-horizontal` and `grip-vertical`

icons/map.svg
=> Fixes `map`

icons/sun-dim.svg, tags.json
| Preview |
| --- |
| <img width="189" alt="CleanShot 2022-03-28 at 19 34 25@2x" src="https://user-images.githubusercontent.com/29014463/160415494-711e926d-3b8e-4a09-bb6e-adb64c7a506a.png"> |
=> feat: dim sun icon

icons/shopping-cart.svg
=> Fixes `shopping-cart`

icons/vibrate-off.svg, tags.json
=> Add `vibrate-off` icon

icons/factory.svg, tags.json
* Icon name: factory
* Use case: Used for representing industry, sectors, manufacture, businesses etc.
* _Screenshots_ of similar icons:
=> Added factory icon

icons/delete.svg
=> Fixes `delete`

icons/bar-chart-3.svg, icons/bar-chart-4.svg, icons/bar-chart-horizontal.svg, icons/line-chart.svg, tags.json
* Icon name: bar-chart-*, line-chart
* Use case: Alternate style for line and bar chart icons.
=> Added alternate line/bar chart icons

site/src/components/CustomizeIconContext.tsx, site/src/components/Header.tsx, site/src/components/IconListItem.tsx, site/src/pages/icon/[iconName].tsx
As discussed in Discord.
Issue:
The customization made by the Customize Drawer was not applied on the icons when clicking on `Download All` button.
=> Fix icon customization in DownloadAll button

icons/train.svg, tags.json
as discussed in #330  
100% scale
=> Add train icon

.gitignore, CONTRIBUTING.md, README.md
=> Extending the Contribution.md description with more topics

icons/siren.svg, tags.json
=> Adds `siren`

icons/utensils-crossed.svg, icons/utensils.svg, tags.json
=> Adds `utensils`

icons/move-3d.svg, tags.json
=> Add move-3d icon

icons/rotate-3d.svg, tags.json
=> Add rotate-3d icon

icons/baby.svg, tags.json
=> Adds `baby`

icons/newspaper.svg, tags.json
=> Add `newspaper` icon

icons/mic-2.svg, icons/music-2.svg, icons/music-3.svg, icons/music-4.svg, tags.json
This one will merge into `main` (original #746)
=> Add more music icons and another mic icon

icons/joystick.svg, tags.json
| Preview |
| --- |
| <img width="241" alt="CleanShot 2022-05-15 at 13 23 52@2x" src="https://user-images.githubusercontent.com/29014463/168463218-3e5a01bc-cca2-4464-a6e6-eaba1fd1ed6f.png"> |
=> feat: add joystick icon

icons/usb.svg, tags.json
=> Adds `usb` icon

LICENSE
=> Fixes `LICENSE`

icons/heart-pulse.svg, tags.json
* Icon name: heart-pulse
* Use case: medical/health, system health check up, pulse/heartbeat
=> Adds `heart-pulse` icon

icons/megaphone-off.svg, tags.json
* Icon name: megaphone-off
* Use case: putting alerts/ads/notifications on silent
=> Adds `megaphone-off`

icons/scan-face.svg, tags.json
* Icon name: scan face
* Use case: face ID, two factor authentication, biometric authentication
=> Adds `scan-face` icon

icons/sun-snow.svg, tags.json
* Icon name: sun-snow
* Use case: represents weather, seasons, temperatures in general, but can also represent air conditioning.
* _Screenshots_ of similar icons:
=> Adds `sun-snow` icon

tags.json
=> Adds airplane tag to plane. Removes plane tag from plane.

icons/concierge-bell.svg, icons/fan.svg, icons/microwave.svg, icons/refrigerator.svg, icons/shower-head.svg, tags.json
=> Adds remaining hotel icons

README.md
It was disappointing not to find Svelte on the main ReadMe page. Fortunately, you guys have already done all the work in creating the package! I'm just adding it to the list.
=> Adding Svelte to the readme

site/src/components/Header.tsx
=> docs: fix click button download zip accidentally

icons/sort-asc.svg
fixes https://github.com/lucide-icons/lucide/issues/805
=> change direction of arrow in sort ascending

icons/heading-1.svg, icons/heading-2.svg, icons/heading-3.svg, icons/heading-4.svg, icons/heading-5.svg, icons/heading-6.svg, icons/heading.svg
=> Add heading icons

tags.json
I upgrade the tags list with adding the tag "maths" and "shape". And with upgrading "social", "code" and "logo".
=> Better tags 1

icons/spline.svg
=> Add spline icon

.github/workflows/release.yml
=> Fix version not bumped in lucide-react-native package.json

site/src/components/Header.tsx, site/src/lib/docsMenuTree.ts
=> Add lucide-react-native package to Header and main menu items

package.json, pnpm-lock.yaml
=> Update husky, automatically install husky on `pnpm i`

icons/check-check.svg, tags.json
Add double check icon.
100%
Contributes to #119
=> Add icon `check-check`

README.md
- Update number of added icons (congratulations to everyone btw, this is impressive)
- Mention official packages
- Expand on "Active community"
Sorry I forgot to fill the commit description, can you manage to do it for the merge commit?
=> Improve "Why choose Lucide over Feather" section in README.md

packages/lucide-angular/package.json, pnpm-lock.yaml
Downgraded the puppeteer version so the angular build can succeed
=> downgrade puppeteer to make angular build work

icons/dumbbell.svg, tags.json
=> Adds `dumbbell` icon

icons/pilcrow.svg, tags.json
100%
Side by side with similar icons
=> Add Pilcrow Icon (paragraph)

docs/index.md
I'm new to the community and I thought the introduction text could need some attention. Thanks for all the work with the icons!
=> Language improvements for introduction text

packages/lucide-react-native/package.json, packages/lucide-react-native/rollup.config.mjs
=> Fix aliases lucide-react-native

icons/alert-circle.json, icons/alert-octagon.json, icons/alert-triangle.json, icons/battery-charging.json, icons/battery-full.json, icons/battery-low.json, icons/battery-medium.json, icons/battery-warning.json, icons/battery.json, icons/file-warning.json, icons/mail-warning.json, icons/power-off.json, icons/power.json
Adds more tags to icons:
* "exclamation mark" tag added to all icons with exclamation mark on them
* "accumulator", "charge" tags added to battery related icons
* "on", "off", "switch" tags added to power-off icon
* "switch" tag added to power icon
=> Add more tags to icons

icons/vote.json, icons/vote.svg, tags.json
Hello! Here is a proposal for the vote icon.
=> Add vote icon (#898)

icons/remove-formatting.json, icons/remove-formatting.svg
=> Add Remove formatting icon

icons/construction.json, icons/construction.svg, icons/milestone.svg
closes #940
Also adjusts `milestone` to match.
=> Adds `construction` icon

icons/router.json, icons/router.svg
Hi Folks, 
I was losing my time on the internet when i came across your project. it matches something i need to do for another opensource project. so I decided to contribute to Lucide by doing a first good issue https://github.com/lucide-icons/lucide/issues/950.
I hope it meets your expectations. 
Happy sunday to all :)
=> [ADD] Router icon

icons/parking-circle-off.json, icons/parking-circle-off.svg, icons/parking-circle.json, icons/parking-circle.svg, icons/parking-square-off.json, icons/parking-square-off.svg, icons/parking-square.json, icons/parking-square.svg
=> Adds `parking-*` and `parking-*-off` icons

icons/package.svg
Centre line is extended too far.
=> Fix `package` icon

CONTRIBUTING.md, package.json, packages/lucide-preact/rollup.config.mjs, packages/lucide-react-native/package.json, packages/lucide-react/rollup.config.mjs, packages/lucide-react/src/aliases.ts, packages/lucide-svelte/package.json, packages/lucide-svelte/rollup.config.mjs, packages/lucide-vue-next/package.json, packages/lucide-vue-next/rollup.config.mjs, packages/lucide-vue/package.json, packages/lucide-vue/rollup.config.mjs, packages/lucide/package.json, packages/lucide/rollup.config.mjs, pnpm-lock.yaml
=> Fix alias support

icons/mailbox.json, icons/mailbox.svg
=> Add `mailbox` icon

icons/door-closed.json, icons/door-closed.svg, icons/door-open.json, icons/door-open.svg
=> Adds `door-closed` and `door-open` icons

icons/arrow-down-left-from-circle.json, icons/arrow-down-left-from-circle.svg, icons/arrow-down-right-from-circle.json, icons/arrow-down-right-from-circle.svg, icons/arrow-up-left-from-circle.json, icons/arrow-up-left-from-circle.svg, icons/arrow-up-right-from-circle.json, icons/arrow-up-right-from-circle.svg
<kbd>esc</kbd>
Related to #1002.
=> Add `arrow-*-circle` icons (including `esc`ape key)

icons/circuit-board.json, icons/circuit-board.svg
Like from [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)…
=> Add `circuit-board` icon

icons/list-tree.json, icons/list-tree.svg
Like `list-tree` from [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html), and a prominent feature in VS Code…
=> Add `list-tree` icon

packages/lucide-angular/src/public-api.ts
=> [lucide-angular] Exports injection token and provider

icons/iteration-ccw.json, icons/iteration-ccw.svg, icons/iteration-cw.json, icons/iteration-cw.svg
Like https://primer.style/design/foundations/icons/iterations-16
=> Add `iteration` icons

icons/workflow.json, icons/workflow.svg
Like `workflow` from [octicons](https://primer.style/design/foundations/icons)…
=> Add `workflow` icon

icons/app-window.json, icons/app-window.svg
=> Add generic `window` icons

icons/columns.json, icons/rows.json, icons/rows.svg
https://lucide.dev/icons?search=columns
Related to #1003.
=> Add `rows` icon

icons/square-asterisk.json, icons/square-asterisk.svg
`key-asterisk` from [octicons](https://primer.style/design/foundations/icons)… Also has more general possible use as password/entry etc…
=> Add `square-asterisk` icon

icons/info.svg
=> Optimise `info` icon

icons/arrow-down-to-dot.json, icons/arrow-down-to-dot.svg, icons/arrow-up-from-dot.json, icons/arrow-up-from-dot.svg, icons/dot.json, icons/dot.svg, icons/redo-dot.json, icons/redo-dot.svg, icons/undo-dot.json, icons/undo-dot.svg
These correspond to `debug-step-*` _[codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)_
=> Add `*-dot` icons

site/src/components/SvgPreview/index.tsx, site/src/components/SvgPreview/types.ts, site/src/components/SvgPreview/utils.ts
=> feat: added radii helper to svg preview

icons/scroll-text.json, icons/scroll-text.svg, icons/scroll.json, icons/scroll.svg
Use case is fairly self explanatory…
=> Optimise/add `scroll`[`-text`] (script) icon

icons/list-filter.json, icons/list-filter.svg
Ubiquitous icon, found in many places including [octicons](https://github.com/primer/octicons/issues/3) and [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html).
=> Add `list-filter` icon

icons/pilcrow-square.json, icons/pilcrow-square.svg, icons/pilcrow.json
=> Add `pilcrow-square` icon

icons/list-end.svg
=> Fix `list-end` icon

icons/search-check.json, icons/search-check.svg, icons/search-code.json, icons/search-code.svg, icons/search-slash.json, icons/search-slash.svg, icons/search-x.json, icons/search-x.svg, icons/search.json, icons/search.svg
=> Optimise/add `search`[`-*`] icons

icons/shapes.json, icons/shapes.svg
Represents `class`ification, a collection of some kind, or learning…
Related to #1055.
=> Add generic `shapes` icon

icons/gallery-horizontal-end.json, icons/gallery-horizontal-end.svg, icons/gallery-horizontal.json, icons/gallery-horizontal.svg, icons/gallery-thumbnails.json, icons/gallery-thumbnails.svg, icons/gallery-vertical-end.json, icons/gallery-vertical-end.svg, icons/gallery-vertical.json, icons/gallery-vertical.svg
=> Add `gallery` icons

docs/.vitepress/theme/components/base/Tooltip.vue, docs/.vitepress/theme/components/icons/CopySVGButton.vue, docs/.vitepress/theme/components/icons/IconGrid.vue, docs/.vitepress/theme/components/icons/IconItem.vue, docs/.vitepress/theme/composables/useConfetti.ts, docs/.vitepress/theme/utils/downloadData.ts, docs/.vitepress/theme/utils/getSVGIcon.ts, docs/guide/packages/lucide-react.md, docs/package.json, pnpm-lock.yaml
=> Small fixes site

README.md
=> Fix latest release link in README

packages/lucide-react/package.json
=> Fix imports poiting to non existent files

.github/workflows/lucide-angular.yml, .github/workflows/lucide-font.yml, .github/workflows/lucide-preact.yml, .github/workflows/lucide-react-native.yml, .github/workflows/lucide-react.yml, .github/workflows/lucide-solid.yml, .github/workflows/lucide-static.yml, .github/workflows/lucide-svelte.yml, .github/workflows/lucide-vue-next.yml, .github/workflows/lucide-vue.yml, .github/workflows/lucide.yml, packages/lucide-react/package.json, packages/lucide-react/rollup.config.mjs, packages/lucide-react/scripts/getAliasesEntryNames.mjs, tools/build-icons/building/generateAliasesFile.mjs, tools/build-icons/main.mjs
Resolves #1482.
https://github.com/lucide-icons/lucide/issues/1482#issuecomment-1667976412
=> fix: generate alias files for nextjs import mapping

.github/pull_request_template.md
Added some clarification to pull request checklists, since multiple brand icons have been submitted, so apparently it wasn't clear for some folks that these requirements must all be fulfilled.
=> [pull-request-template] Clarified that all requirements must be fulfilled

icons/bring-to-front.json, icons/send-to-back.json, icons/send-to-back.svg
=> Improve [`send`/`bring`]`-to-`[`front`/`back`] metadata

docs/guide/packages/lucide-preact.md, docs/guide/packages/lucide-react-native.md, docs/guide/packages/lucide-react.md, docs/guide/packages/lucide-solid.md, docs/guide/packages/lucide-svelte.md, docs/guide/packages/lucide-vue-next.md, docs/guide/packages/lucide-vue.md
Improve clarity and readability of packages guides in docs.
=> Improve clarity and readability of packages guides in docs

packages/lucide-solid/package.json
closes #1558
This PR allows TypeScript to access the type declarations for the Solid package. It does this by allowing access to the file in the package.json's "exports" field.
=> Fix Solid type declarations

icons/image-down.json, icons/image-down.svg
This can be used when exporting/downloading something as an image.
=> feat: added image-down icon

icons/backpack.svg
=> Optimized `backpack` icon

docs/guide/design/illustrator-guide.md
In the line no.23 of file illustrator-guide.md, fixed a typo by changing 'unecessary' to 'unnecessary'
=> typo fixed

icons/armchair.svg
=> Optimized `armchair` icon

.github/workflows/pull-request.yml, scripts/updateContributors.mjs
=> feat: added lint-contributors job

icons/cake.json, icons/cake.svg
=> Fixed gaps in `cake` icon

packages/lucide/rollup.config.mjs, packages/lucide/src/lucide.ts
=> fix export IconNode type

docs/.vitepress/lib/SvgPreview/index.tsx, docs/.vitepress/lib/SvgPreview/types.ts, docs/.vitepress/lib/SvgPreview/utils.ts
=> feat: added curve handles to svg preview

docs/public/framework-logos/angular.svg
Angular v17 comes with an updated Angular logo, we should update the old logo used on the site as well.
=> Update Angular logo on site

packages/lucide-angular/package.json
closes #1695
Update the peer dependency for the lucide-angular package to support version 17 of Angular. I'm using lucide-angular in my Angular 17 projects without any issues. This will solve the need to use `--legacy-peer-deps` when running `npm install`.
=> Support Angular 17

icons/crop.json, icons/frame.json, icons/frame.svg, icons/grid-2x2.json, icons/grid-3x3.json, icons/grid-lines-offset.json, icons/grid-lines-offset.svg, icons/grid-lines.json, icons/grid-lines.svg, icons/hash.json, icons/layout-grid-move-horizontal.json, icons/layout-grid-move-horizontal.svg, icons/layout-grid-move-vertical.json, icons/layout-grid-move-vertical.svg, icons/layout-grid-plus.json, icons/layout-grid-plus.svg, icons/layout-list-move.json, icons/layout-list-move.svg, icons/layout-list.json, icons/list-ordered.json, icons/list-ordered.svg, icons/list.json, icons/list.svg
=> Optimise `grid`/add [`layout-`]`grid` `move`/`list` improvements + metadata

icons/pointer-off.json, icons/pointer-off.svg
To mark something as non interactive. "you can't touch this"
=> feat: added pointer-off icon

icons/bowl-chopsticks.json, icons/bowl-chopsticks.svg, icons/bowl-overflow.json, icons/bowl-overflow.svg, icons/egg-cup.json, icons/egg-cup.svg, icons/meal-box.json, icons/meal-box.svg, icons/mortar-pestle.json, icons/mortar-pestle.svg, icons/sushi-2.json, icons/sushi-2.svg, icons/sushi-3.json, icons/sushi-3.svg, icons/sushi-chopsticks.json, icons/sushi-chopsticks.svg, icons/sushi.json, icons/sushi.svg, icons/toast.json, icons/toast.svg
Possibly closes #1396 and #1323. Related to #1289 and #1306.
=> Add additional food icons

.github/workflows/pull-request.yml
Tested at https://github.com/jguddas/github-icon-worflow-test/pull/18
=> chore: pull-request workflow refactor

docs/guide/packages/lucide-react-native.md, packages/lucide-react-native/README.md, packages/lucide-react-native/package.json, pnpm-lock.yaml
=> Add support for react-native-svg ^14.0.0

icons/bag-hand.json, icons/bag-hand.svg, icons/bottle-perfume.json, icons/bottle-perfume.svg, icons/gem-ring.json, icons/gem-ring.svg, icons/gem.json, icons/glasses-square.json, icons/glasses-square.svg, icons/glasses-sun.json, icons/glasses-sun.svg, icons/glasses.json, icons/glasses.svg
Closely related to #1473.
`glasses-sun` related to #1393.
=> Refine/optimise `glasses`/add fashion/accessories icons

icons/gavel.json, icons/gavel.svg
=> Fix `gavel` gap

docs/.vitepress/lib/SvgPreview/utils.ts
=> fix(ci): made cp1 in preview absolute for smooth curves

packages/lucide-preact/src/createLucideIcon.ts, packages/lucide-preact/src/defaultAttributes.ts
Fix type error of preact `createLucideIcon()`
=> Fix type error of preact `createLucideIcon()`

.eslintrc.js, .npmignore, CONTRIBUTING.md, scripts/generateChangelog.mjs
I was trying to set up the site locally to fix an issue and I noticed that `CONTRIBUTING.md` file hasn't been update after the `site` folder had been removed in this commit - https://github.com/lucide-icons/lucide/commit/5bfc736b61cd42b57c35f16ebb8b92b2db24116c.
=> Remove mentions of the site folder in doc and config files

.github/actions/build-and-test.yml, .github/actions/check-icons.yml, .github/labeler.yml, .github/workflows/ci.yml, .github/workflows/close-stale-prs.yml, .github/workflows/labeler.yml, .github/workflows/linting.yml, .github/workflows/lucide-angular.yml, .github/workflows/lucide-font.yml, .github/workflows/lucide-preact.yml, .github/workflows/lucide-react-native.yml, .github/workflows/lucide-react.yml, .github/workflows/lucide-solid.yml, .github/workflows/lucide-static.yml, .github/workflows/lucide-svelte.yml, .github/workflows/lucide-vue-next.yml, .github/workflows/lucide-vue.yml, .github/workflows/lucide.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml
Bump github actions
The artifact workflows v4 seems to have many issues, so for now, I've only updated to v3. (Ref: https://github.com/actions/upload-artifact/issues/472)
=> Bump github actions

docs/package.json
closes #1771 
Fixes the `pnpm docs:dev` build command when started for the first time.
=> Add nitro prepare command docs site

.github/workflows/pull-request.yml, scripts/lintFilenames.mjs
#1781 has not been the first time we have had miss spelled icon names.
This PR adds a script that we can run on every pr that add annotations to files that are missspelled.
=> feat(ci): added filename lint job

icons/list-collapse.json, icons/list-collapse.svg
This PR adds a new icon `list-collapse`, shown below.
This icon can be used for a set of collapsed sections. For example, [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) elements in the Lucide's pull request bot comment.
=> Add `list-collapse` icon

docs/vercel.json
- Site
Adds cache header to site assets so caching will be done on client site as well.
See example deploy: https://lucide-i3ntvvah0-lucide.vercel.app/
=> Add cache header site assets

icons/text-search.json, icons/text-search.svg
A combination of `search` and [`text`](https://lucide.dev/icons/text).
Self-explanatory.
=> Add `text-search` icon

icons/bolt.json
Missing `contributors` (me! :)
=> Fix `bolt` missing metadata

icons/arrow-big-down-dash.svg
=> Update `arrow-big-down-dash` icon

icons/rss.json
=> Update `rss` icon metadata

icons/anchor.svg
=> Update `anchor` icon

icons/file-symlink.json, icons/file-symlink.svg
This aligns the design with the suggested change of folder-symlink in #1618
=> Update `file-symlink` icon

icons/telescope.json, icons/telescope.svg
closes #1854
Adds telescope icon as requested in #1854
See #1854
=> Adds `telescope` icon

icons/anvil.svg
Fixes missing corner rounding in `anvil` as per #1865
=> Fix `anvil` rounding

packages/lucide-react/README.md
=> docs: fixed import statement of `dynamicIconImports` in README

icons/bot-message-square.json, icons/bot-message-square.svg
Like standard `bot` added in #1544, but with [`message-square`](https://lucide.dev/icons/message-square) outline, to emphasise *chat*bot. See [below](https://github.com/lucide-icons/lucide/pull/1709#issuecomment-1832716243).
1. Start new chatbot conversation
2. Indicate response
=> Add `bot-message-square` (chatbot) icon

icons/area-chart.json, icons/arrow-up-right-from-square.json, icons/bar-chart-2.json, icons/bar-chart-3.json, icons/bar-chart-4.json, icons/bar-chart-big.json, icons/bar-chart-horizontal-big.json, icons/bar-chart-horizontal.json, icons/bar-chart.json, icons/candlestick-chart.json, icons/file-bar-chart-2.json, icons/file-bar-chart.json, icons/file-line-chart.json, icons/file-pie-chart.json, icons/line-chart.json, icons/pie-chart.json, icons/scatter-chart.json
closes #1942
closes #1921
- Metadata
Adds tags
=> meta(icons): Update metadata

icons/cannabis.json
=> chore(icons): remove non existing smoking category from cannabis.json

icons/hotel.json, icons/hotel.svg
Optimized icon by manually moving things around.
=> fix(icons): optimized `hotel` icon

icons/hospital.json, icons/hospital.svg
Completes https://github.com/feathericons/feather/issues/1178
Adds a hospital icon as per https://github.com/lucide-icons/lucide/issues/119
- hospital
- emergency room
- various medical institutes/buildings
=> feat(icons): added hospital

.github/pull_request_template.md
=> docs: changed precission check list entry 

icons/tram-front.svg
=> fix(icons): fix tram front icon dots

scripts/generateChangedIconsCommentMarkup.mjs
=> chore: always fold `Icon as code` preview comment

.github/workflows/lucide-angular.yml, .github/workflows/lucide-preact.yml, .github/workflows/lucide-react-native.yml, .github/workflows/lucide-react.yml, .github/workflows/lucide-solid.yml, .github/workflows/lucide-svelte.yml, .github/workflows/lucide-vue-next.yml, .github/workflows/lucide-vue.yml, .github/workflows/lucide.yml, .github/workflows/pull-request.yml, packages/lucide-preact/package.json, packages/lucide-react-native/package.json, packages/lucide-react/package.json, packages/lucide-solid/package.json, packages/lucide-svelte/package.json, packages/lucide-vue-next/package.json, packages/lucide-vue/package.json, packages/lucide/package.json
Splits up build and test in two jobs.
If it fails it clarifies what is failing.
=> ci: Split up jobs in workflows

.github/ISSUE_TEMPLATE/03_bug_report_site.yml
Add more OS in the `ISSUE_TEMPLATE`: This includes ChromeOS, iOS, and Android to ensure the report is concise as possible.
=> refactor: add more OS in `03_bug_report_site.yml`

.github/ISSUE_TEMPLATE/02_bug_report.yml
Add more OS in the `ISSUE_TEMPLATE`: This includes ChromeOS, iOS, and Android to ensure the report is concise as possible.
=> refactor: add more OS in `02_bug_report.yml`

icons/grid-2x2-x.json, icons/grid-2x2-x.svg
This PR contains `grid-2x2-x` icon that helps grid icon scenario.
- error data tables
- disabling or removing grid feature
- could signify that particular task within the grid has been removed or deprecated or failed
=> feat(icons): added `grid-2x2-x` icon

docs/guide/packages/lucide-static.md
=> fix(docs): fix uppercase import in lucide-static docs

docs/.vitepress/data/teamData.json
Changed my name in the teams section and changed lego -> LEGO
=> docs(site): changed my name in the team section

packages/lucide-angular/package.json
=> feat(angular): add support for Angular 18

packages/lucide-angular/README.md, packages/lucide-preact/README.md, packages/lucide-react-native/README.md, packages/lucide-react/README.md, packages/lucide-solid/README.md, packages/lucide-static/README.md, packages/lucide-svelte/README.md, packages/lucide-vue-next/README.md, packages/lucide-vue/README.md, packages/lucide/README.md
Fixes license typo by "`ICS`" to "`ISC`".
=> Fix license typos

icons/section.json, icons/section.svg
replaces #2045 originally added by @gurtt
=> feat(icons): added section icon

icons/lectern.json, icons/lectern.svg
replaces #2032 originally submitted by @gurtt
=> feat(icons): added lectern icon

icons/tv-minimal-play.json
=> fix(icons): fixes duplicate tv-2 alias

.github/workflows/pull-request.yml
Check that there are no overlaps between icon names and aliases, aliases and names need to be unique.
=> feat(ci): check uniqueness of aliases

.github/workflows/pull-request.yml
This time actually tested https://github.com/jguddas/lucide/actions/runs/9628032092/job/26555817323?pr=10
=> fix(ci): fixed check uniqueness of aliases action

icons/cloud-moon.svg
=> fix(icons): changed `cloud-moon` icon

docs/.vitepress/lib/codeExamples/createLabCodeExamples.ts, docs/icons/[name].md
Fixes lab code examples. It was using the kebabcase name instead of the camelcase what should be used.
=> fix(site): Fix lab code examples

tools/build-helpers/src/shuffleArray.mjs
Fixes Generate comment markup github action.
=> fix(tools): rename `shuffle` to `shuffleArray`

icons/type-outline.json, icons/type-outline.svg
Used to represent type outlines (in WYSIWYG toolbars for example).
Added `type-outline` icon.
Used to represent type outlines (in WYSIWYG toolbars for example) or text stroke.
=> feat(icons): added type-outline icon

icons/image-plus.json, icons/image-plus.svg
=> refactor(icons): changed `image-plus` icon

docs/guide/design/icon-design-guide.md
=> feat(icons): clarification on naming overlapping elements

packages/lucide-angular/src/lib/lucide-angular.component.ts
closes #2315 
Our Angular package has crappy change detection, icons should be replaced in case any property is changed (not optimal, but till a complete rewrite of the lib, it is what it is).
=> feat(packages/lucide-angular): fix change detection on icons

icons/calendar-search.json, icons/calendar-search.svg
=> fix(icons): changed `calendar-search` icon

icons/omega.json, icons/omega.svg, icons/sigma.json
Adds uppercase `omega` icon (Greek letter).
1. **Physics and Engineering:**
- Representing ohms, the unit of electrical resistance.
- Symbolizing angular frequency in oscillatory systems.
- Denoting the Omega constant in various equations and formulas.
2. **Mathematics:**
- Indicating the last element in a set or sequence.
- Denoting the space of all functions in certain contexts.
- Representing the omega limit in dynamical systems.
3. **Astronomy:**
- Naming certain celestial objects or constellations.
4. **Philosophy:**
- Representing concepts of the end or finality, often paired with Alpha to signify the beginning and the end.
5. **Greek Language:**
- As a letter in Greek writing and typographic contexts.
6. **Education:**
- In educational materials for teaching Greek letters or …
=> feat(icons): add omega icon

icons/circle-check-big.json, icons/circle-check-big.svg
=> fix(icons): changed `circle-check-big` icon

icons/tickets.json, icons/tickets.svg
Added new `tickets` icon.
Multiple of ticket.
=> feat(icons): added `tickets` icon

icons/folder-search.json, icons/folder-search.svg
=> fix(icons): changed `folder-search` icon

icons/chart-gantt.json, icons/chart-gantt.svg
Added new `chart-gantt` icon.
To show gantt charts and timelines.
=> feat(icons): added `chart-gantt` icon

docs/.vitepress/theme/components/home/TeamMemberCard.vue
Added wrapping of text to team card.
=> style: added text-wrap balance to TeamMemberCard.vue

docs/.vitepress/api/gh-icon/[...data].get.ts, docs/.vitepress/api/gh-icon/diff/[...data].get.ts, docs/.vitepress/lib/SvgPreview/Backdrop.tsx, docs/.vitepress/lib/SvgPreview/Diff.tsx, docs/.vitepress/lib/SvgPreview/index.tsx, scripts/generateChangedIconsCommentMarkup.mjs
Will add new section with a diff for the icon to the PR comment.
The diff will look like this:
=> feat(pr-comment): moved diff into separate section

CONTRIBUTING.md
=> fix(docs): fixes yarn workspace guide link

icons/grid-2x2-plus.json, icons/grid-2x2-plus.svg
Added new `grid-2x2-plus` icon.
- add item to grid
=> feat(icons): added `grid-2x2-plus` icon

scripts/generateChangedIconsCommentMarkup.mjs
=> fix(pr-comment): changed diff path url

scripts/generateChangedIconsCommentMarkup.mjs
=> fix(pr-comment): added missing details open tag

icons/briefcase-conveyor-belt.json, icons/briefcase-conveyor-belt.svg
Added new `briefcase-conveyor-belt` icon.
Indicate when luggage is being transported.
=> feat(icons): added `briefcase-conveyor-belt` icon

icons/message-square-lock.json, icons/message-square-lock.svg
Added new `message-square-lock` icon.
To show that your message is encrypted / secure.
=> feat(icons): added `message-square-lock` icon

categories/charts.json
Category icon name was still using the old name.
=> fix(categories): fixed `charts` icon name

docs/guide/design/icon-design-guide.md
This PR updates the grammar in the `icon-design-guide.md` file to improve clarity and readability. No content changes were made, only corrections to grammar and sentence structure.
=> Update icon-design-guide.md to improve grammar

docs/guide/packages/lucide-angular.md
closes #2567 
This PR updates the documentation to include a clear example of how to use LucideAngularModule within standalone components in Angular.
Before
After
=> (docs) update lucide angular guide for standalone components

icons/undo-dot.svg
=> fix(icons): changed `undo-dot` icon

docs/guide/packages/lucide-svelte.md
Fixes #2490 
Updated the documentation's direct import syntax for icons.
=> update code example for lucide-svelte direct import

scripts/generateChangedIconsCommentMarkup.mjs
Fix `scripts/generateChangedIconsCommentMarkup.mjs` when no changes are made. It sometimes fails when it tries to generate a comment based on no relevant changes.
=> ci(pull-request): Fix generate comments for empty changes

docs/guide/packages/lucide-svelte.md
- [ x] Documentation update
fixed the pnpm pkg installation cmd https://pnpm.io/cli/add
=> docs: update lucide-svelte.md

icons/heading-4.json, icons/heading-4.svg
=> fix(icons): changed `heading-4` icon

icons/vegan.svg
=> fix(icons): changed `vegan` icon

packages/lucide-svelte/package.json
=> fix(lucide-svelte): Replace file extension build config

.github/workflows/close-issue-with-banned-phrases.yml
related to #2616
add `bluesky` to brand filter
=> chore(ci): add `bluesky` to brand filter

packages/lucide-angular/package.json
Closes #2637
Add support for Angular 19.
=> feat(angular): add support for angular 19

docs/.vitepress/theme/components/icons/IconsOverview.vue, docs/package.json, pnpm-lock.yaml
=> fix(docs): Fix empy icon page

README.md
The phrase "personally use" is grammatically incorrect. The correct term is "personal use" because "use" is a noun in this context, and "personal" is the adjective that modifies it.
Fixing documentation in the License section of the Github README
=> Fixed typo in License section of Docs

packages/lucide-svelte/scripts/license.mjs
The license text is included in the license comment to make sure it ends up in SvelteKit bundles. Fixes #2709.
=> lucide-svelte: Make sure license ends up in SvelteKit bundles

icons/expand.json, icons/expand.svg
=> fix(icons): changed `expand` icon

docs/.vitepress/theme/components/icons/CarbonAdOverlay.vue
=> fix: Hide add if script is blocked

packages/lucide/tests/__snapshots__/replaceElement.spec.js.snap, packages/lucide/tests/replaceElement.spec.js
=> chore: fix typo

.github/workflows/lint-code.yml, .github/workflows/lint-pr-title.yml
Make it so that if you update the title of the pr the action reruns.
=> fix(ci): run lint pr title on title change

CONTRIBUTING.md
Corrects capitalisation and tense of a couple text elements.
=> fix(docs): grammatical inconsistencies

CONTRIBUTING.md, README.md
closes #2887
- [ x ] Documentation update x
Contributors image was not appearing in both README.md and CONTRIBUTING.md. I resolved the issue by adjusting the width to acceptable standards to render as it was not a network or cache issue.
- [ x ] I've read the [Contribution Guidelines](https://github.com/lucide- icons/lucide/blob/main/CONTRIBUTING.md). x
- [ x ] I've checked if there was an existing PR that solves the same issue. x
=> fix(docs): Resolves #2887

icons/newspaper.svg
=> fix(icons): arcified `newspaper`

icons/clock-fading.json, icons/clock-fading.svg
Added new `clock-fading` icon.
When time is fading away.
=> feat(icons): added `clock-fading` icon

.github/workflows/close-issue-with-banned-phrases.yml
this brand has been requested 3 times already:
https://github.com/search?q=repo%3Alucide-icons%2Flucide+pix&type=issues
=> feat(ci): added `pix` to brand filter

icons/banknote-arrow-down.json, icons/banknote-arrow-down.svg
closes #2931 #1677 
Added new `banknote-arrow-down` icon.
Can be used in financial applications, payment platforms, economic reports, or any interface indicating a decrease in money, balance, or income.
May also signify withdrawals, payments made, losses, or deductions.
=> feat(icons): added `banknote-arrow-down` icon

docs/.vitepress/data/packageData.json
Typo fix for @lucide/astro badge
=> Typo fix for @lucide/astro badge

icons/text.json, icons/text.svg
=> fix(icons): changed `text` icon

docs/guide/installation.md
closes #3024 
Just added documentation to segment for preact to match all the other packages.
=> fix(dev): added link for preact in installation

CONTRIBUTING.md, docs/.vitepress/config.ts
Closes: #3047, #2912 
Adds `studio.lucide.dev` to the site and `CONTRIBUTING.md`.
=> docs(studio): Add lucide studio to site navbar

CONTRIBUTING.md
I noticed while there was an @jguddas if one clicked on it it wouldn't lead anywhere so I added the link
=> fix(docs): Added link for jguddas next to lucide studio

CONTRIBUTING.md
There were multiple grammatical and spelling issues found in the CONTRIBUTING.md file/ contributing guidelines portion of the website:
1.  <img width="275" alt="Image" src="https://github.com/user-attachments/assets/6164418b-a62a-4f7a-a7ac-046d938f6f2b" />
2. <img width="266" alt="Screenshot 2025-04-20 at 11 26 47 PM" src="https://github.com/user-attachments/assets/8b419bff-2418-4eb4-a557-66d8a114fb47" />
3. <img width="564" alt="Image" src="https://github.com/user-attachments/assets/8f2868f6-0c0a-443d-9dc5-2e24c1e7cf50" />
4. <img width="253" alt="Screenshot 2025-04-20 at 11 35 24 PM" src="https://github.com/user-attachments/assets/d5fec3a6-e448-4c02-b9b1-34268bc434c2" />
5. <img width="589" alt="Screenshot 2025-04-20 at 11 36 09 PM" …
=> docs(CONTRIBUTING): Grammar fix for CONTRIBUTING

icons/orbit.svg
=> fix(icons): changed `orbit` icon

docs/.vitepress/data/packageData.thirdParty.json, packages/astro/package.json, packages/lucide-angular/package.json, packages/lucide-preact/package.json, packages/lucide-react-native/package.json, packages/lucide-react/package.json, packages/lucide-solid/package.json, packages/lucide-svelte/package.json, packages/lucide-vue-next/package.json, packages/lucide-vue/package.json, packages/svelte/package.json
closes #3023
Added periods at the end of summaries to keep consistent feel on website
=> docs(pacakges): Added periods to package summary

.github/pull_request_template.md
Links to comment under #1687 regarding adding Pr Title conventions to template
Added comments to PR template to guide new contributors on how to title their PRs so they can know before failing the check.
=> fix(docs): PR Conventions

icons/door-closed-locked.json, icons/door-closed-locked.svg, icons/door-open.svg
=> feat(icons): add door closed locked / unlocked icons

icons/users.json, icons/users.svg
=> fix(icons): changed `users` icon

icons/clock-plus.json, icons/clock-plus.svg
Added `clock-plus` icon.
* Create a new timer.
* Adding a new clock (e.g. New York, Amsterdam) to a dashboard.
* Create a time supplement profile.
=> feat(icons): Added clock plus icon.

icons/square-pen.json
=> fix(metadata): added tags to `square-pen` icon

icons/search.json, icons/search.svg
=> fix(icons): changed `search` icon

icons/bomb.json, icons/copyleft.json, icons/copyright.json, icons/creative-commons.json
closes #3086 which @alirashidy brought up
The 4 icons below are missing categories causing them to not appear when the category nav is not open but only appear when the all button is activated: 
- bomb.svg
- copyleft.svg
- copyright.svg
- creative-commons.svg
=> fix(Icons): Adding missing categories to 4 Icons

.github/workflows/labeler.yml, .github/workflows/lint-code.yml, .github/workflows/lint-pr-title.yml, .github/workflows/linting-icons.yml, .github/workflows/lucide-font.yml
Reduces speding cost on github runs.
=> fix(ci): reduces workflow triggers

icons/bell-electric.json, icons/bell-electric.svg
=> fix(icons): changed `bell-electric` icon

icons/menu.json, icons/menu.svg
=> fix(icons): changed `menu` icon

docs/guide/advanced/accessibility.md, docs/guide/advanced/aliased-names.md, docs/guide/packages/lucide-angular.md, docs/guide/packages/lucide-astro.md, docs/guide/packages/lucide-preact.md, docs/guide/packages/lucide-react-native.md, docs/guide/packages/lucide-react.md, docs/guide/packages/lucide-solid.md, docs/guide/packages/lucide-static.md, docs/guide/packages/lucide-svelte.md, docs/guide/packages/lucide-vue-next.md, docs/guide/packages/lucide.md
Closes #2705
Make sure we are using the latest icon names in our documentation. So changed the names to current version.
=> docs(packages): Update names in docs

docs/.vitepress/theme/components/base/Switch.vue, docs/.vitepress/theme/components/home/HomeIconCustomizer.vue, docs/.vitepress/theme/components/icons/SidebarIconCustomizer.vue
Reverts lucide-icons/lucide#3005
Resolves #3194
=> revert(site): resets Absolute Stroke Width

icons/square-dashed-top-solid.json, icons/square-dashed-top-solid.svg
Added new `square-dashed-top-solid` icon.
UI Design Tools: Used to show that a specific side of a component is selected for editing, such as adjusting width, color, or style
CSS property selection: Represents a control to set the border width or styling for one specific side of an element.
=> feat(icons): added `square-dashed-top-solid` icon

packages/lucide-angular/package.json
=> feat(angular): update peer dependencies for Angular to support version 20.x

icons/pocket.svg
Optimised paths in Lucide Studio
=> fix(icons): changed `pocket` icon

icons/spotlight.json, icons/spotlight.svg
closes #2555 
reopen #2572
Added new `spotlight` icon.
- highlight the winners, feature, or person on stage (virtually and physically)
=> feat(icons): added `spotlight` icon

.github/workflows/close-issue-with-banned-phrases.yml
=> ci: add "telegram" to close-issue-with-banned-phrases

.github/ISSUE_TEMPLATE/01_icon_request.yml, .github/pull_request_template.md
=> docs: add rule against war/violence related imagery

icons/rail-symbol.json
=> fix(icons): deprecate rail-symbol

LICENSE
resolves #3528
copied from https://github.com/feathericons/feather/blob/main/LICENSE
=> fix(license): add full text of Feather license

icons/wallpaper.json, icons/wallpaper.svg
=> fix(icons): changed `wallpaper` icon

scripts/generateChangedIconsCommentMarkup.mts
add link to lucide studio to x ray images
=> feat(preview comment): add link to lucide studio to x-ray images

icons/cog.svg
=> fix(icons): optimized `cog` icon

icons/panel-left-right-dashed.json, icons/panel-left-right-dashed.svg, icons/panel-top-bottom-dashed.json, icons/panel-top-bottom-dashed.svg
Moved dashes to match rest of the icons.
=> fix(icons): changed `panel-top-bottom-dashed` icon

docs/.vitepress/data/packageData.thirdParty.json
Added a new Flutter package to support Lucide icons in Flutter projects.
=> feat(packages): add new package for flutter
